### ISSUE TITLE
hot bar sometimes randomizes repetitively

### ISSUE THREAD

**Issue by stayandwait** [PocketMine/PocketMine-MP#4158] opened 2016-04-30 01:36 UTC
I'm using Minecraft Windows 10 Edition to connect to the server I created. When I change to a different item in my hot bar using scroll on the mouse, it will randomly select between 2 items repetitively.

Steps to reproduce:
-Use the middle click scroll wheel to select items in the hot bar, scroll select as much as you can with the mouse.
-You should now see randomizing between 2 items happening. It's quite irritating.

PocketMine-MP: 0.14.0
PHP: 7
OS: Windows 10

**Comment by extremeheat** [comment] 2016-04-30 02:16
I've also seen this issue. It's not just limited to inventory swapping, but picking up items and dropping them.

The client and server get stuck into a nearly endless argument that results in packet spam from both directions.

Simple solution that I've seen is to just acknowledge the change and not send the echo the packet back unless it's not a legal action.

**Comment by stayandwait** [comment] 2016-04-30 02:19
How would I do that?

**Comment by Pub4Game** [comment] 2016-04-30 04:09
However, this works fine in a MiNET so it is confirmed

**Comment by extremeheat** [comment] 2016-04-30 05:38
Yeah, MiNET doesn't seem to echo the packet back to the client so it fits in with my findings :p

Anyways this may be an issue with slot mapping  differences in the Windows 10 Edition. But the easiest way at least in my opinion is to just not echo the packet back.. that way we can avoid potential side effects in PE.

**Comment by dktapps** [comment] 2017-12-31 11:19
This has long since been fixed on PMMP's PocketMine-MP.

**Closed by dktapps** 2017-12-31 11:19 UTC
