### ISSUE TITLE
Gamemode not crafting bug

### ISSUE THREAD

**Issue by thedeibo** [PocketMine/PocketMine-MP#3356] opened 2015-08-08 10:28 UTC
Bug for the 1.6 Dev. (Build 7 Beta)

basically, I got my server on default gamemode creative, so when people join, they can't build.
 - although I did find a way to bypass that bug. Change gamemode from creative to survival, and back again.

bug: http://t.co/SCKJCzihSg

( i dont know if i post it here, or on Twitter, so ill do them both )

**Comment by sekjun9878** [comment] 2015-08-08 14:26
Duplicate of #3357

**Closed by sekjun9878** 2015-08-08 14:26 UTC
