### ISSUE TITLE
Player Not Moving

### ISSUE THREAD

**Issue by ChaostixZix** [PocketMine/PocketMine-MP#4230] opened 2016-06-27 21:02 UTC
I Opened "Player Not Moving" Issue A Few Days Ago
Someone Says It Was Fixed In The Last Commit, But I Still Cant See Other Player Moving, And Othe Player Cant See Me Moving

And There Is A "Lead" Between Player

![screenshot_14](https://cloud.githubusercontent.com/assets/19998246/16395615/0f2852d0-3ce5-11e6-9be3-03c877fc421f.png)

**Comment by btarno** [comment] 2016-06-28 00:28
I can confirm this has been fixed in the last commit.  My players are now seeing each other move, however now they can't build anything..

**Comment by btarno** [comment] 2016-06-28 02:15
I was wrong, this doesn't appear to be fixed.  I have downloaded all the most recent files and I now the players are no longer showing that they move.  I have no idea what files I was using to make that work before.  What branch was this issue fixed in?  Master?  Because I have the master synched up and when two people join, they have a permanent lead to each other that I can't disable, and they can't see each other move.

**Comment by jojoe77777** [comment] 2016-06-28 02:24
@btarno Where did you download the files? Works for me. If you have git type 'git clone https://github.com/PocketMine/PocketMine-MP --recursive' in a terminal/console.

**Comment by btarno** [comment] 2016-06-28 03:11
I just completely deleted the entire directory and cloned your master from github with the command above.  I'm also using the PocketMine-MP_1.6dev-27_ef8227a0_API-2.0.0.phar file and the PHP_7.0.6_x86-64_Linux.tar.gz file.  Still neither player is showing as moving.  I must be doing something wrong.  In a last ditch effort I upgraded my server to Ubuntu 14.04.4 LTS.

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty
uname -a
Linux ****** 3.13.0-91-generic #138-Ubuntu SMP Fri Jun 24 17:00:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ChaostixZix** [comment] 2016-06-28 04:13
i'm installing it using phar file, so, how to install it from github, im new at this

**Closed** 2016-06-28 08:07 UTC
