### ISSUE TITLE
Level is loading to slow

### ISSUE THREAD

**Issue by Sulfatezzz** [PocketMine/PocketMine-MP#2575] opened 2015-01-27 20:13 UTC
When im switching to an Level (to an chunck which was not loaded) i will not spawn at the spawnpoint (I will spawn under the spawnposition)

*sorry for my bad english

**Comment by andrewnoelcasper** [comment] 2015-01-28 20:47
This is caused by the chunk not being loaded and the player falling through the chunk.
But this is Invalid

**Comment by ztdroider25** [comment] 2015-01-28 22:48
I have the same issue.  @iksaku said you should convert your (anvil?) world to mcregion to avoid those errors.  It could also be caused by a bad chunk as @andrewnoelcasper said.

**Comment by MobileCrafter** [comment] 2015-01-28 23:56
We(Sulfatezz & me) already use MCRegion and it happens on all worlds.

**Comment by ztdroider25** [comment] 2015-01-29 23:41
Oh, sorry didnt know that.   Can you send me those converter files?

**Comment by MobileCrafter** [comment] 2015-01-30 12:43
http://www.mediafire.com/download/13g2zdwq6ram09u/Converter.zip
Look at the bat for more info.

**Comment by ztdroider25** [comment] 2015-01-30 17:40
Thanks so much

**Comment by sekjun9878** [comment] 2015-03-21 11:26
Issue seems solved. Closing.

**Closed by sekjun9878** 2015-03-21 11:26 UTC
