### ISSUE TITLE
used up Stone Pickaxe re-appear

### ISSUE THREAD

**Issue by ixquisite** [PocketMine/PocketMine-MP#2531] opened 2015-01-11 22:51 UTC
Used up Stone Pickaxe re-appear when you walk into items mined with it.
Keep mining with a stone pickaxe continuously until its getting removed from the bar. After it has been removed, walk into some of the e.g. cobblestone you mined to collect it. Stone Pickaxe(s) will come back (single & multiple)

**Comment by Darkrift411** [comment] 2015-01-20 14:59
I can confirm this issue exits and have some extra info that may or not be useful.

The dead pickaxe will generally be usable to break 2 blocks after it re-appears. It will then disappear, and sometimes it will take an item with it. Example, 
*I have torches in slot 2 
*slot 3 has stone axe 
*Stone axe gets used up and disappears
*stone axe re-appears in slot 2 where torches were
*using stone axe twice (successfully) and it disappears
*torches no longer exist in inventory

This has happened about 3 times for me, and I was not able to determine why it was appearing in a diff slot than what it was before, nor whether the torches disappear when the ax re-appears, or if it disappears when the axe disappears the second time (meaning I havent been able to check if they just get pushed out of the slot on my action bar)

**Comment by unerds** [comment] 2015-02-04 00:09
confirmed.

dev956

**Comment by unerds** [comment] 2015-02-10 07:24
there is another issue i think is linked to this one, apologies in advance for this hopefully not too lengthy elaboration:

i had a stone pickaxe that was glitching as described here.

i made a crafting table, but could not place it... it would just reappear in my inventory.

i just gave up on it for a while, and went on using my pick, it would break and come back...

i then tried to dump these items into a chest, and they would revert to my inv repeatedly... after multiple attempts they both remained in the chest - i crafted a new table and i was then able to place it.

seems like there is some kind of inventory corruption when crafting items...

also, i recall when crafting the glitched tables, that the quantity of planks in my inv didn't seem to change (may be mistaken on that, as i wasn't paying really close attention) so maybe there are issues with updating inventories - items lost and items gained sort of thing....?

hope that helps.

**Comment by Darkrift411** [comment] 2015-02-10 07:25
What you are talking about is what is referred to in another issue as
transaction rollbacks.

**Comment by dhecker** [comment] 2015-06-20 19:37
Also seeing this one. Makes it very hard to mine!

**Comment by Kanonen** [comment] 2015-07-20 19:15
Seeing this in build 1257. When the stone pickaxe gets to zero durability, it seems to instantly respawn in my inventory. Often, it will also 'appear' twice in the inventory - not a true duplicate, but two inventory UI slots that link to the same item.

I can then use the resurrected took for another break or two, and then it does it again.

Wouldn't have to do with some issue where the durability value is going below zero, and wrapping around or being rounded up or something, would it?

**Comment by keuin** [comment] 2015-07-21 14:31
I have the same problem.Both 1.4.1 and dev 936.

**Comment by Kanonen** [comment] 2015-07-21 21:23
Think I found the bug. StonePickaxe.php is setting the item to iron tier, so the max durability is wrong. So the client side sees the item as reaching max durability, but the server does not.
http://jenkins.pocketmine.net/job/PocketMine-MP-doc/doxygen/d2/dbc/_stone_pickaxe_8php_source.html

**Comment by Addison118** [comment] 2015-07-22 18:13
@Kanonen I have already fixed this in the "new-blocks" branch. It looks like it's not been merged with the main branch yet.

**Comment by Kanonen** [comment] 2015-07-28 14:54
Confirmed that this is fixed in the newest development build (1258)

**Closed** 2016-02-17 11:26 UTC
