### ISSUE TITLE
Invisible players

### ISSUE THREAD

**Issue by DanielZ123** [PocketMine/PocketMine-MP#2904] opened 2015-04-17 11:44 UTC
Some players are invisbile.

I using last dev version.

**Comment by PEMapModder** [comment] 2015-04-17 14:10
Are you sure they are invisible or are they somewhere else? Possible duplicate of the clone issue.

**Comment by LDX-MCPE** [comment] 2015-04-17 15:10
I can confirm this bug. They turn invisible after they die, and they don't reappear until either you or the invisible player quit and re-join.

**Comment by NML32** [comment] 2015-04-17 20:14
I've seen this with some skins.

**Comment by iJoshuaHD** [comment] 2015-04-18 06:33
would it be buggy to do this per 20 ticks and will fix the issue?

foreach($this->getServer()->getOnlinePlayers() as $p){
 foreach($this->getServer()->getOnlinePlayers() as $_p){
  $p->showPlayer($_p);
 }
}

**Comment by PEMapModder** [comment] 2015-04-18 09:12
Use spawnToAll or spawnTo instead. showPlayer won't spawn if the server thinks the player is already visible.

**Comment by TruDan** [comment] 2015-04-18 10:00
The server thinks the player is already spawned to the cilent. It's a bug with both MC:PE and PocketMine. It can also happen while teleporting (over long distances).

**Comment by Guillaume351** [comment] 2015-04-19 09:05
This bug happen when you teleport a player. You can see him doing round-trip from the initial position to the arrival position sometimes. But when he moves, you can't know where he is

**Comment by JoahDave** [comment] 2015-04-28 03:19
Confirmed. This does not always happen when players die and I can't seem to figure out what causes it.

**Comment by ZhyMC** [comment] 2015-04-30 09:44
I think it's the problem of PocketMine.It doesn't make players invisbiled some builds before.

**Comment by LDX-MCPE** [comment] 2015-05-01 06:36
I have discovered a new cause. Players turn invisible when their name tags are changed. I have tested this thoroughly.

**Comment by ZhyMC** [comment] 2015-05-01 07:43
I KNOW THE WAY TO PROTECT PLAYERS FROM INVISIBLING. JUST DON'T CHANGE EVERYONE'S NAMETAG . WHITE NAME IS OK!

**Comment by DanielZ123** [comment] 2015-05-01 10:46
ZhyMC, you are right.
Some players after change NameTag are invisible.
It's confirmed. I tested it on my server for 2 hours.

**Comment by iJoshuaHD** [comment] 2015-05-07 11:57
invisibility bug exists when a player1 came from a chunk that player2 isnt loaded.

**Comment by DanielZ123** [comment] 2015-05-23 15:25
And when player change nametag
h

**Comment by shoghicp** [comment] 2015-05-28 23:40
This might have been fixed by f133154919e8fe340972e4beb12b2ba7b6d478fe

**Comment by iJoshuaHD** [comment] 2015-05-29 06:13
the bug still exists.

**Comment by TruDan** [comment] 2015-05-29 08:39
I dont get any invisible player bug o.O even before the fix commit


Sent from my Samsung Galaxy S5

-------- Original message --------

**Comment by DanielZ123** [comment] 2015-05-29 08:55
Maybe new build fix this?
https://plus.google.com/112518133011799486490/posts/1rY2RTRAg4t
"Fixed invisible clients"

**Comment by SuperPitty** [comment] 2015-05-29 22:30
I ever do tp with EssentialsTP, and i tp to other player, the player get invisible

**Comment by shoghicp** [comment] 2015-05-30 20:33
Do you have *networking.async-compression* set to true? If so, disable it and try again, because that'll be part of the issue.

**Comment by Vladik46** [comment] 2015-05-31 13:57
Does not work.

**Comment by iJoshuaHD** [comment] 2015-05-31 22:47
mine is set to false.

**Comment by SuperPitty** [comment] 2015-06-05 13:49
Oh, i don't know..

**Comment by RaymanT** [comment] 2015-06-07 13:30
Can reproduce, Player1 is a world (not default) and then player 2 get teleported to Player1 and player1 cant see Player2.

**Comment by shoghicp** [comment] 2015-06-07 13:32
Is this happening on the latest build?
This happens due to MCPE not liking players on unloaded chunks, and blocks further movement updates. There is a workaround on the latest build after players move some chunks.

**Comment by RaymanT** [comment] 2015-06-07 13:38
I used Build 1225

**Comment by shoghicp** [comment] 2015-06-09 15:15
I'm not able to reproduce this anymore.

**Closed by shoghicp** 2015-06-09 15:15 UTC
