### ISSUE TITLE
On Windows systems, the provided binary has xdebug enabled by default, imposing a function nesting limit.

### ISSUE THREAD

**Issue by manh994** [PocketMine/PocketMine-MP#3053] opened 2015-05-21 07:17 UTC
Error: Maximum function nesting level of '100' reached, aborting!
File: /src/pocketmine/event/server/DataPacketSendEvent

<s>http://pastebin.com/W3QfubyC</s>
http://pastebin.com/YqN7C4w5
<s>http://pastebin.com/Ma8H4XA6</s>

**Comment by manh994** [comment] 2015-05-21 07:18
Sorry for my English

**Comment by sekjun9878** [comment] 2015-05-23 08:14
The first pastebin is a duplicate of #2576. The last pastebin appears to be caused by SimpleAuth, please file an issue there.

**Comment by shoghicp** [comment] 2015-05-23 09:19
You seem to be using outdated PHP binaries.

**Comment by sekjun9878** [comment] 2015-05-23 09:58
Looks like this issue happens on Windows systems, where xdebug is enabled by default therefore xdebug's default max_nesting_level of 100 is imposed. **As a temporary workaround, in the `bin/php/php.ini` file, you can follow [this guide](http://stackoverflow.com/questions/4293775/increasing-nesting-functions-calls-limit) to increase the nesting level to something really high to avoid this issue.** This issue is present on both the current stable, beta, and latest Jenkins Windows PHP binaries. We'll look into fixing it and close this issue once it has been resolved with the latest binary.

Thanks for reporting this issue!

**Comment by sekjun9878** [comment] 2015-05-23 11:39
Fixed with https://github.com/PocketMine/php-build-scripts/commit/633ea39e746acedc40e7e6465e3e5ebfb5c18f2d.

**Closed by sekjun9878** 2015-05-23 11:39 UTC
Labels: C: Core, Debugged, Reproduced
