### ISSUE TITLE
Compound::$item

### ISSUE THREAD

**Issue by Artide** [PocketMine/PocketMine-MP#3433] opened 2015-08-31 06:29 UTC
No new plugin or changes, just updated pocketmine and started getting so much crash dump. Heres the crash: 31.08 01:18:19 [Server] Server thread/NOTICE UndefinedPropertyException: "Undefined property: pocketmine\nbt\tag\Compound::$Item" (E_NOTICE) in "/src/pocketmine/entity/Item" at line 72

**Comment by flaxues** [comment] 2015-09-13 19:33
maybe post a CrashDump

and it think this is a duplicate of #3461

**Closed** 2016-02-17 11:16 UTC
