### ISSUE TITLE
tp command error

### ISSUE THREAD

**Issue by vvzar** [PocketMine/PocketMine-MP#3557] opened 2015-10-04 12:07 UTC
[15:06:33] [Server thread/CRITICAL]: Unhandled exception executing command 'tp  th eg' in tp: Uninitialized string offset: 0
[15:06:33] [Server thread/NOTICE]: StringOutOfBoundsException: "Uninitialized string offset: 0" (E_NOTICE) in "/src/pocketmine/command/defaults/VanillaCommand" at line 48

**Comment by SkygridRex** [comment] 2015-10-04 18:01
tell me what version of PocketMine you are using and you most write the name complete when you use tp

**Comment by vvzar** [comment] 2015-10-04 18:31
Try to explane it to children. they are using tp only as they want :) Build 1263. Pm1.5dev. Our task is expecting such  mistakes and making correct workarounds.
Survival is fully useless in pm1.6

**Comment by PEMapModder** [comment] 2016-02-19 10:50
This issue is caused by adding an extra space behind the command.

I reproduced this even just with one player:

```
"/tp pemapmodder pemapmodder "
```

Note the space before the closing "

**Closed** 2016-02-19 10:51 UTC
