### ISSUE TITLE
Running through saplings causes damage

### ISSUE THREAD

**Issue by Darkrift411** [PocketMine/PocketMine-MP#2593] opened 2015-01-31 17:51 UTC
I planted rows of saplings and while running through them I was taking damage. Issue requested by Shoghi.

**Comment by Falkirks** [comment] 2015-02-01 17:40
I can't reproduce this.

**Comment by Darkrift411** [comment] 2015-02-01 17:52
I just re-tested on a different device (tablet vs my phone). I was able to duplicate it for the third time.

Plant a row of saplings 1 block away from each other, then do the same thing one row over:

x[_]x[_]x[_]x[_]x[_]x[_]x[_]x
[_][_][_][_][_][_][_][_][_][_][_]
x[_]x[_]x[_]x[_]x[_]x[_]x[_]x

x=sapling, [_]= empty dirt.

Run through it but not in a completely straight line (not sure why this matters, just makes it happen more often). I kinda zig-zag through so that I am going from one row to another. I start taking damage.

While I was typing this I had my 2 daughters try it and both of them took damage just by running through it at an angle. 

The server has been restarted twice this I first noticed this and we are in a completely different area than when I first noticed it. Also it is on a large flat plain with no other blocks that could cause this such as stairs or half-blocks.

When I first noticed this, Shoghi stated that this was a known issue that he had resolved in the latest dev, but I am running on 954 (the latest dev that is available on the site at the moment) and it is still occurring. He asked for this issue to be opened so he could look into it again.

**Comment by shoghicp** [comment] 2015-02-15 17:50
This was caused by trees growing but not showing up on clients. This has been fixed by 3a157d0f02051b233e3e6b0ca24a59bf1c4c23fb

**Closed by shoghicp** 2015-02-15 17:50 UTC
