### ISSUE TITLE
Water not filling surrounding area properly

### ISSUE THREAD

**Issue by Darkrift411** [PocketMine/PocketMine-MP#2584] opened 2015-01-29 18:57 UTC
When I am digging dirt blocks at the bottom of a lake, the water should fill in the missing blocks, but instead I a getting pockets of air. I tried to fill them in with a bucket but something is wrong with that also.

**EDIT**
After having other issues I decided to save and restart the server. Aftwards all of the air bubbles that should have been water were now water. I was not having load issues on the server, so I am not sure why it took a restart for this to work properly. Based on this, I do not know if this is an actual issue. If nobody can duplicate it may need to be closed.

**Comment by jingz2007** [comment] 2016-04-13 22:21
I dont know if it is the exact same scenario, but I exploded a TNT block to remove a small natural bridge between two islands. The water fills in the top of the hole, but anything under is air.

**Comment by dktapps** [comment] 2017-12-31 11:37
Duplicate of this issue (now closed): #4326

**Closed by dktapps** 2017-12-31 11:37 UTC
