### ISSUE TITLE
Player Not Moving

### ISSUE THREAD

**Issue by ChaostixZix** [PocketMine/PocketMine-MP#4212] opened 2016-06-18 14:44 UTC
Me And My Friend Joined The Server, My Friend Is Moving, But I Can't See Him Moving,And He Can't See Me Moving

### OS and versions

* PocketMine-MP:1.6dev
* PHP:7
* OS:Centos 7 64 Bit

**Comment by robske110** [comment] 2016-06-18 14:48
I don't know if PM is gonna fix that, I gonna make a PR
In the meantime (until the pr is merged) you can try out a fork of PM [estimated time of merge: INF]

**Comment by extremeheat** [comment] 2016-06-18 16:58
Duplicate of #4207.

**Comment by robske110** [comment] 2016-06-24 18:37
Fixed

**Closed** 2016-06-25 09:48 UTC
