### ISSUE TITLE
an E_Error

### ISSUE THREAD

**Issue by pomee4** [PocketMine/PocketMine-MP#3418] opened 2015-08-26 17:58 UTC
Please help me!

PocketMine-MP Crash Dump Wed Aug 26 19:46:55 CEST 2015

Error: Call to a member function hasPermission() on null
File: /src/pocketmine/Player__32bit
Line: 439
Type: E_ERROR

Code:
[430] 		return $this->perm->isPermissionSet($name);
[431] 	}
[432] 
[433] 	/**
[434] 	 * @param permission\Permission|string $name
[435] 	 *
[436] 	 * @return bool
[437] 	 */
[438] 	public function hasPermission($name){
[439] 		return $this->perm->hasPermission($name);
[440] 	}
[441] 
[442] 	/**
[443] 	 * @param Plugin $plugin
[444] 	 * @param string $name
[445] 	 * @param bool   $value
[446] 	 *
[447] 	 * @return permission\PermissionAttachment
[448] 	 */
[449] 	public function addAttachment(Plugin $plugin, $name = \null, $value = \null){

Backtrace:
#0 (): pocketmine\Server->crashDump()

PocketMine-MP version: 1.5dev #1254 [Protocol 27; API 1.12.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux mcpelinux 3.16.0-4-686-pae #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) i686
PHP Version: 5.6.10
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
XperiencePvP 1 by Darkgod for API(s) 1.12.0
EconomyAPI 2.0.7 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
iProtector 3.1a by LDX for API(s) 1.9.0
EasyMOTD 1.0a by LDX for API(s) 1.12.0
SimpleBroadcast 1 by Dutok for API(s) 1.0.0
EssentialsPE 1.1.0 by LegendsOfMCPE Team for API(s) 1.12.0
PurePerms 1.1.3 by 64FF00 for API(s) 1.12.0
XperienceLaggmentesito 1.1.0 by Darkgod for API(s) 1.12.0
EconomyShop 2.0.5 by onebone for API(s) 1.12.0
SignShop 1.1.2 by xionbig, xionbig for API(s) 1.11.0
AlwaysSpawn 2.2.2 by Philip Shilling for API(s) 1.12.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
LiveSigns 1.2.1 by aliuly for API(s) 1.12.0
NetherChests 1.1.1 by aliuly for API(s) 1.12.0
MCG76_WorldEdit 0.5.2 by minecraftgenius76 for API(s) 1.8.0
XperienceBelepes 1.7.1 by Xperience-Darkgod, DarkGod for API(s) 1.12.0
TapToDo 2.2.1 by Falk for API(s) 1.0.0
XperienceStatisztika 1.1 by Darkgod for API(s) 1.10.0
PureChat 1.2.7 by 64FF00 for API(s) 1.11.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtfQt327ix8F/BdbbfJq31fljmXu+tYyuOW9nWWkqy21WXByIhiRFFsnz4kT5++50ZgCRIUbKz
TXrPd85uGxEYDAbAYDAzePrvB7GzEQdGq9tt9lutdqt3eCDC0A8PjL8fxI8BJB0MzeHt7c3tweHB
RkQRXyLsjLsui33G2UZs5iJki8SzYsf32IpHYxFunCiC2MtXDEBe4rqQe+G4mLURhVYj8K21iDeO
Jxpjlz+K0DQ77bkTA5oLwAOj2zn+5+FB4CZLxzswFtyNxOGB5dsCK9btNIHQLJ7FoYiT0GPfxCsn
qn0fQMG17x2tAhMRv/zG4xvx6jsg3e20KN8/KdyGMAU6BGz8/vcU61KM/Z79MeAh37AgIzab5YT/
EcWh4y0ZEad8PZWPIv2MiKrh3PddSjlSKQ2KDSgWJHPXsXbxUNb/74R/vKfdVbmo1d1m3upuS7W6
29Zb3e2UWj0mzrNvVA8gSpkxZQ50eyUEbDNj7Js77iYSo6/xqHtU5lE1p0/jmFurjfBiyjXQ+dc9
ruQft+0818tiUw5lhdkJm81QMA9V/TIAcBokLw65BbL288GLJnv5ymC5wM5mExHeibD2vRXyaHWe
bIKXrw7+eniwFJ4IuYsCCslYdahcq96zxR3UdZ44rg0Drd3rglyHfuxbIBFG++jwgAcOYbba9SZg
LmEYGAfNZ/4HGUK+dp055qkfEYWEusQ4GDle8sA2ViBcCnXqrX69WevW+oN+LeCCvWixydWYnYu5
wz2ZfFSz1nGrVWuxl+1mq1dr9mrt7ivmQBagHKwCoNur9+stLOiT8KBNB22IN2Wq6UdpwQCgCJV9
kI3mCBn0I/S1IzxLjO/GGFcVLoAPcza2gElJvPLDCLvknIfrpW8jz4l1P6e8A4Dw+NwVUKk4TEBj
2CKAKmIuSIv8RXyuAzYclcvBiG/m/mx25m/mPB75y6UIZ7MrTmLv+hxbOL6ZTD/c3I7OAXQv5pET
Q3VRWqBZQ8v3/M3j6fhSa4kG1NoBnII+Oii0xvfEHP4VWtMkdkKr1LedfVv07ah4R8W7Kt6F+K9k
gqrGbCZkzaEus1mhFc9ghTMGwRZWLO2HYoUG1FkBdedFTozOfyxw4fjf6NLzH2ezvOBndefBKo6D
yGg0YACuknnd8jcNoFO7OhsPG1ojsMt59Hh1Mz3XOzwFHRZGf/OJNv5bcouNTMv995uYtQAaOHE2
gSteh0DL4lGstbOcsnuUJrG/3pLqX9nUUqmgg7eq8ZyRGkVgEBxwJsZDvet0cLH75ADU+08ssXI3
C2QZmwq++WLdqVdjNhtBc0T4a/qTaigr2Cg0DTgwTkKBpjXSmp/Dym3vFNve775502x+sfaakh7Y
+rQCWjBv+GR6ejt9N36q2ZRTGphGTgWanNmUEV8u0SEQQMSvMjpFhCcE4UsboTNX8BBr8KW6PiN4
kNuoycoPto0UQctWqve0lXqyuboV/AzTE0F9MtujKveM0T1xll6pgRmo3JntYuseIGXuLAGYhgrt
bP07ikvWADVWVpcn+xW6VVWkLpKG8psaGQVo7Kl7zx+jScDvPa29OrTYoe1yk8crx3UCNoEPOGjL
LybHAdGNFNnZjFOVIqzStmRXjG3VmZlmF7oroUNLXdovNm9457sTqOIXa5dWdNnU7tJQ0Iv39/d1
AVVBqvV4jT03cu4E9qSugnNYsVXS39OaxV0ncR+/WKMkudnMhfIjLP9XexHcFR+5Z4c+UNRm97VU
dmHGKhobYl8jby2w41rEKxGerUQU6xwpgMuj9z/DFE9YWPx/hCWF5gJXrs4ujvrmBz907aHt6P5X
OUXnDWjt8jDHEmGeuojBMjhJdNQvsGnw67m0sZZH/dlMNmY2u8cKCajQbJbVDc3x5TMnUZkRfi1c
KC2qss9pUlEcjsrikOHXUht9SNb64gtaa+l+nkKhqSuK4f0qAXXBQ1q3+irBfp7yYOqf695ICimr
71Ij33D3iznXMQ9i34YZcF725/TYJOaxE32KnTWv6jU9WZ8s1J8xqf/sRh2MaZxdgTvxCKVd8SgC
ZaNciYPD4rT8wnftSUxFlob+GqxXyGPxOcsA6HSerXhc8qwJVNbqR0871k/5HJrbvs2FN5wWwiKY
tB7scLixXnno33a3icg/cZEHl/4E6LS0f2ixrB6EPghE7ODIPngxzmLszPcWzpLh4vAsnHkvPgib
nSZL1u6z1sDo9Yxul50NJ1OGq1GIIQnWAj+MT1rHrU4bgRux8cPHmutsnPik3ewOrhC65Ai3xUmT
cPgD6F5cbI5OWk0CkVtSC+TUHhh20kLo/QqaDbSiWGaUfVD7WyLCxxPf00AhiJOCbPzYPsmEnqEL
jmDueX6CukiWXOPWyhF3AqcZkcrJXde/ry1cZ7mKT/zFIq8Y95wNTN0UnoRt/HkKWPghEM4aKYEr
HtqWH4qUUnAXqBTbWSwcK3HjxxPimVyvjP2wFok4BmctOkGwC9VzayjBJ9H6EbLnwEgIW8PB/YGT
N6PTKYKQFfUAxhtYAvvk9/QftC2J/VrE79La4SJhZgnrjxsXpYHhIGMWCUICNcIlXJQHBg1kakCj
4bwag3ywKRhJwdIqMx4KBraTwYiPIMBjZiHPYzYXzPEsNwGrBAG2JYdIa+JvIOcCCZRpRnwhDpmP
ZjlCkmweCr5mj34SKlrMWTBgvLNwqARgeghSBOrDQyGVpIwZlLxKYtvHrpPbJwab5dqRrR2oNgwg
V2z+y3g1O4AML05RIhgKIC6wK3+B3Tmc/YAyCCgki6knYTBUDpgRZgf3jCMrIx/4pwpk9yvhAVii
syQCToEigdqCioPRNr4ETFBGNvBES6hBG+d+JHLyQ5L6lA74NgwljQFPobuwqvNHyL/gIGOArsZI
lmow2saZ4fr8HYe22zULhoPI4UngBTXo9HuQ4UKGFxPUbFCi7z1u/CRiERmV2LEi3IWyoGtiAQ3D
xoYCVQM2JYJMtUSyPG3CdULbVdDnp9GjZ015tGYgsWvoZUz+cHp7fXl9YYCUQb/cgxnAngXyIB5L
159zl0lVIws7ZPMkZk4MJLxvSeSw06TAoVDGfszdOrYYC6upggzWQhmxxTxZooC8uFyw71nrkAhh
kRF2IyWnXRilFFXXQi4ag0Qq7ZiINZAvCbYEdPQGOiiTjXwI54L5AoZS2l841jYweGgEEapqPkiL
lB/JZJtEhLLUZBaDbSBpibs2silkqbCiID9xxBahvwHh0+kDa3GExlrx0Ivxdm1AEaBZoo67mQ5V
t8D/rQQGmweDjQiRA0YrNzY1nUrOqqeEaOZZq8Rb11AqULhooIEweTFKA6VFKDJUF2UncEuKgZSt
Z7Q7VcOgwbqY9czfwEChHSrJL+SULVmlilBE6+wtqHYgdALqAobL2fjdIWSJIjaHHrp37HglpUl2
W0q1pjp4sLuiPASozQSMIlVjwEUzJ5EM1u7184Zj5dOGX/EHxss0YaRaULZQFLfa3e43Me8tt2Em
oeVT1eCqDtSXMi9+aiHhK7Y9vxvJHtaSwAapi3JVYOGyFlWILPRW9yqrBgykhn5Y0cwK6xQmcgjl
GChfnKFdFCF1/Apk3GZgdXyJio6TgiKxizwnjQ0c79iPS9eJrdVjRS6pIAjZ5UvqfyT0LkLxiKWO
ge5fwCyQZfaYWANKGIYwCBIxA2SrRjok12TQhfXtPoR2KjoiE14wYx6wGK2pRidlaN6/LY2LliGT
HN+uOR4hQCf0wW0CHIrVIBWRpJNSI+8EexlRoKEezmszKGop9AXQFSAyiETav4Yd6iWBwY4lcenm
kCdHWiqlBVSOMJcqEIn2MHrPsaAMSDC+mYN1jSWK8kKkXTBSa8Jo9za1FsQcJf+4bJVaLzvjNxkT
PIBQhGT6tAANVoED7lkGXPkoqVRiXfN/PBFn1ZOCThwtFw26QKYasr2hV1NmIEORUD/QfIEz9FlQ
o4IW8QMcViCMIuYo3mAmoAQ0TKBtQPhDtMUr8JtQ4chEpcwTklSuk2FqLqPZq2QJJgo8LyCxlJIt
mKKHLJHJaQlRiS04L65giuuA0SUJGD5w1AzKmfLvgbqqgpHWBVNAtKLYB0H6GYM1jnv7CPgrKRNo
FaTgF+OACcz72UMdg3EwYEts+894HAYdQWbzR0igZY3MWOo+IjXch+JDxxa6XkH2Qv4ql5NcJnL3
I7JryKoNmDsHWqeMLllz2V4qlSpAIYbeN44v0qN5aQZDF9xof3d02Dt+aB12HjqH7e9a39mgQKSy
eokrTRYqipNBky1BCiMZ6/ZekUsuHmLhIRtp2eUMlJS+yY+Sp8dBVy6zIzmBhcgqEv0NFKHoyJMI
NXnu4ZM8miB3sOcWWORVfp6HuzBaeJgD5JGjNJaEbhYBH5LWgoF0S27GLOIgS13aeXCTg1cw4OQ2
LOB/jAqrqsRvWx6baNV7qrqbuTzWkpEA5+YxiPMmxhxrbOsMmYxHRAWX3gILzFme+RFYQkckVIj1
6lh/LIzVcErbbvaaHQh+cwl927H6g8G8P59bnabd6fNFh1ud7sK2u/OjeW9+NDhaiB78x76BksYr
ZBzt1VDBfuQ85N0izU+kEFrY4FuxcOU0F6BUnlgsBnPb6vfmzbngi8Giy23RXzT7i0F3IPp2t2Mv
7AHMxLG8aLXxc85GNGCjYksdyUxAjv218JxPaYcB5APMnkDXSEbVcbX+kdP0L13Q/eQE6SmYHp0W
kTqUthQo9BKEdfx2zN7LIc9OvmeyC1BdTB5hRG8Q9oUPvcy813hyh52jRQXyfwIvotWl1QjW7Bm9
Y6PXmXlnavIK3p10vBGVfVtvpLNa8S1EazU1J3I8POUG+hrUjfOJBum3mIza2Hk4adzxsAHjpvFR
eGtcYfkIk/4GtL2mzYapnQ2cUoDFtEQDXUeYNDeo1Q06TdeYO14DuNcj4uJBWF+3BPRlajhqvyZ9
VChfm37NdsKvWQaK/tekL5XW1ywBtOzXJB94y6/dB0s7C/tJXPNAbsHfKMBQheJAzTMpo/G1RqjU
DqkN0mGpqdRh91Kl6qBU7xPMdiIC4loaKtACECr/sHELoHLc9jeFeEQTtIpcWKQIy9D7EJyBItRa
OkWKcqpbLBXXPQqQwPYL3RIIxYcU4OCUv4hi+zXpjWgy5VgFVq2K3CTfQwcoE1cAQR5hn3h+AYhr
UdbJoyihgrks9CrMCmP4B5OVT3Gxg8CpDeNazJcFCp9ofuEswRUuwMnF0AF4AtuGeWJNGuFCodLt
0DQDoZzocIUqfbMCR4q0wEDrUXC/NKWJdb3bnFzcTG90JD+gSZ7k2NnZydLCPjgDj/ViclK7aQPq
Ynx5hlk2PLRWJ2hyKRYnnjgJ8PBSsukiZOH5MC2NqItu2vh7PvlhdDkdmm9P3w/Ny8n16XWKhy2p
gWsuO2qReLiaK6G6zY1SfOQy8A/8FT+DxSEPwO9Y1lK2LBaOhxsDkgzMqFNMWv4oYCqSHJc9ax5X
BaEbXrujQ4TgGhHIh1lubYE7JrXAB/mQ4wUrfI9LCjXXhzkdgZw7qHmkNwfTKpoDFt52wM2DKRCu
IPie0iQLOtIc5jWh/A4N8UUocMG/hut4NNcmoPUgp+HAmRAmdlTjTQdZPzpXPfjBPayFATT75Ntv
v/3mm5vby4vL60a9jroRIJAhwwBa3roaDUViPJYkMfzjjyfLP/xBhn4Tlf+fReVb8MzlZgnuMoBP
nLrHYBsFu8RWLKComffeCeOEu+zcCanVj2ySBLg0g5nUgkjuZss1uDe4R/QSrGcduP2KjYGliP3F
bTMSm3l0dslmFVXAMlf+RjRw0pHnUgGsHHABt5BowQ/cGlpt4rbtIA1oNKLQjleEtF56vidgrnNa
iRDwEFdoNTycEynuwqyk02o1+xI4TKf1WVK7DUl/wdWvYtrORDn3ARQoIMM6nE7KBRTwdLRz2sXI
kj1/5k3lKusEBDN+LHQvFT6h0cDegpTQntIWwpXcgLniHl/iqvpWOq6ozB9huqaJUBD6dw723/yR
pf7VzLsc3/UrBe18iiNAT1K22sbJ5q2SfSCHbJjAGOEb6rt0/b6Os4hDBt1/SP12SLtHh8zmMT9k
uJ8OcPxBL+SQgWktUJUU2YTklUFdvEguU0IRsQXZEht/POcBg8uqvG9ovYRyYF3qvz9kclZAIVtk
YcmLeujHrU4Wi31ouQi1uOvfa3H8BCZ6LNlOD9LCZclkI2xoqKCFZOQWLfYD/5d4J2jD1yDEuKkk
t12Z7HMLyNFm5wi0R4LbeENcScQ1MCmRFGN3dNPkEAZh8Bji2h17ab1irePjQY0m5IQ7haI9qO+S
Nnnxf8z8Mv9JagUNgADpOWHo9dkVKqGoQqJApki1gbKlVQofPHr2Xt48+h6EGXtPxlOC9Qidfkxt
0g+tzqtpANVDhXcUd0Z7DXuWTJ5fH1qyNGFeby58sLOIcKN+9US13U4Ji4X6IAKeADUDP0hcHgsz
5PcQiWITB4PePB4uzUjgARIwAKDygoTa9P/op5wMXn45PZISuVV+EvsmGGhglrlQ+trz2V3a1jSs
MOU2b2R+dOJSQzEVRvczCM1D/x56L9iNoTY6TWuF+pxKSuJFbYCBd9M3tUGOsnE2AucmNPjFQ9xY
xRu3EMGzHaSdTMvlUSTNyI5yFWJ6V24/Km7omXQflPAm0/Obd9M8lOPAHAjsd6DhKr5hB9i+ZYa+
H+8pyrdgImtCe57E2U9Iyr9pu8WuU+BM6ky0QMq4aFhY+VRS1O3G3SURMmiZp1BSiXkeQbkfpRCb
JYwHJzZ9z8Q9Cl/Kvi7n4gHaB41cBaVmpVbaRNfjazlIGGjkGwkN8GtpJo+T3VrqEvzflj7zcNSa
SYB7L1GRSSuwJrTjXJfbrsTd/174EIjiR1eczA4ssCmhwV68eTPA/cuD71XovxuI9v1nZ9ALTc89
7KSBVz1fv0YaMvRkoTsy6IWmemQ3AVlrGXpWiRUZ9BLX4hGPh+2jcXSU0sDQMwqtzKAXmg+8ahLn
52m9ZejJMndkgDKBoboK1AYnOLVgj3F40ymaZ2JFfhJaYgcWOFGgrebK8hcQNoHrWKAsFm4SrYqC
roy0GajZUt2Qv5gCBtUUnuXbexUVzT3Bqj8DFdTjjpbmKeaGP5iu9CpazXY3/eKBTcetwzTJfDBX
tMJYJkIIdAoSTUfIzfzw6e46Uaa9ehsrhJslCRpI0ra6l4KpZT3SbspfmSoZ6Qk6vmfKw0GQ3O/K
Xx0pJV5ryV89DfRkJJnRbKbf9KSrSbPtPGerPbiaeeicmXMO80Op6KubJz0nc57gsRfd0jSztKd7
ViGucJYm9hRGJhfbFDmfKGlwJX8hCdxPJ3VLW7LfgTlgml0UTpNWDrN8rf6f1WcLJY5dyYOm+iCG
nA+Z4DRa+HNXHAXSzJrATFfwdVSZiGuapjyFV5K7UPwtgd41QZXtazseBUFpM+kI3NNo6ZBktZjV
HKYF6dSzw13ghVlk25H8BQRcQzZJAsAJLtd4cjUdY8RFNx+PXRQikHsTB2Y6iWj35C+A/+bWcQHJ
xAPGZZoROPWx2ATmXmnDpaT1DiWQaM2CqrhzREXPdDc5OejMdBCm0tG+kr8ZQvxUvUh7Po3heE69
IGUdORg7OBYzDKyKfFUCVClCacFGj8w8GM4OndLMxWZ4MT6bZIGZh1spgSWZZXrypKo2OPXkLV6i
tIIbgQfZzcRzrLTDMqkmBOUIL62KtE22blJFOqIp+jM0g8SmRRyY3QhrXSYHs1iczmQBVpiLaDNY
3Emm77vbUeUklxIuPXnQU42Io3q3VW/WzofvZ97pkurWmXlvwJ4mIa4H0LHf1fk18f0nhJzBFAzm
9KQhrv10yUpFLiaT2rVY+rGj9v8ReHl+nQVxBSmltA7n3TRhBEpHpLNESgU39VMWuZ6OrlJUDH94
ncYm4+vhxU0Wm4yyPJOJXOVD+HQ0qU1ux2l0rB4UIRbKBaeFWmOK0vUmusUx896q0f8w6Jv9bi3x
1p5PB+7As64tvUSWqa0YjH2XhwBr4HsTMC/9y8iZ6+l4oGZAB5rxxoz6NuRBqqqViYMbN/Lhw6aA
8sn3BJ6t4Gi2dKq4nlMHc7CNBImpC4Kdpc4Pp2g4mhI8cdV4ndg8wAt8n7XWgZVP3XHTBbGK1ZJG
p1U/6vePtGAZ2feWOXav3u50OlpQYUeJFzowTYNh4kh1f9ys9wYdhZxFcvRIxM/F3sOF4iDF6aZY
qrVM8cCgS0Me0mrs6wRNus1cBdIGpDyDhaFLWpwBljm2HHm4pi+XHMtrtrfiLjNXdOpo0AcTPZ/z
Xn9g9Xqt41aXd3r9Tl9Y3eZg0RJHoo9Hn9rsm8/rOVk7fSoldz9wwakYK+OCn6zWjapVGuDHAX7e
gBWtXm1b0u/FeeVqMoA1yZ4rBr9s46sCtGQMPATMV4B5+Ybd0up4FRlIPJNXHaqSx9cXlXDoSEwq
jNh+HX2GD6+vxpVZfnx9VQn/nO5Y2vWPgViaaraCB1RLzibgbAL1qWTrBVTvLq92Hy85Ij4e60u/
lRnfQgIWJpeNqWc3dhv+deFfj0Ur3sKfNsw28NPr46czoFiv1WZg6sTGBqc6DfWbKoS4MtQBd/N+
5YRugM9cxc5ShJDhsKOC/WYWPG5nQUDo5gjdHAGK9sQiTNQHi1miosafGq3V+4yjqw3jwgqt9HfO
Ft5dC2L44eoLEw2Kwvejz3nMVhwEWVZOBqlyMkiVoyBwIwv2+hkCVTnL1s2zdfNs3TxbN8/Wy7P1
8my9PFsvz9Zj2KF4RDP9VnYsJdwVbU8ru91iz7VgZf40LVsq0oll50BzvFQJFopskbXLd5FmXuWW
U1ZonqqWIoTczUAX3Jlv5guwY2+noFrkknfmYsW47+Nmnk2+A6VyFWvVqbf1amlNLOy5zA4i2iCi
m1xr7n10GPmKUiOqS120oQOa/uAQRdxaMdq3RMLzBK83gQbDuwUrwS6u37ERXhoJmbwd4bKxfI1t
5FhQvsgqidquyKuXH3nAYXiKV3j+GqxQtJd5Euel7+HmS7LhrxjOF2h+wXJH09uf5U7fCTmu9z5P
p6XMTR3tJyaAGXrapWapSwuLGSkyusMmnizHiUxh5SHFQE/OzPZHniibkPPdkudjmygH2e4DKdFf
XtKewz94gAtM1IzGA+1AzP4As5NXz8HRCvuMlaQsj5tuEGKySGKUuDyoIeIHukj21D5+RwmEwHGL
Be3GcCve16eQkdRxHqoUW5lkqlFVhaH7uvUeetCngQPOvHR+m+1WG0200icw5iwnWKmFLXyGpIbW
iUxE6HwE70+4BInv/YUDVpGH1gKvqhIqWhPXXzvHRxrycZvuuIaBm0TsHlQEm7v+PWauSZeE2dDp
GT4ZScDGpXHQLDzDhhY5yw1nodVmuCsMjYN8es1x8UDWe24xazFnVhwyYc2ZhxHPhx/8J/US+8wR
Kfexubv0Q/CQN9H+Ob1CpxrtxwRcOipHKgtDl9UnUly8aETnLypsxRc+9Q8iIrkyxiKADVDyyPHk
+lUTvXK+N13l1kGfxWtiSF1u+NLiESihdIqbLyYU0IK8JlVIqQOeLknt6LUictoJnU6zn363ke6f
TU8e9Hw2Oi7pPIlMi9opn9956nBUIVLALfLpiQx4N9DzoNe2dJpK99Vamu/JJVLbDLAy2ysxSkC1
4C4d9cVFWb9AC/SjVF3MPLpUrhY+NDA5NHiERyXhlVEtOT1ZJte1Wboy2G0e93ESyrdSOu2j/kAl
aVuqnVavIy8ongEbcWiAXdLum2fLRnmquhJeRKJVGrAmqVlr8OwMWXqjP2frIa0zm3Tu7hBfBjEl
jknppsdxgJrp8woVGHQtNkOAoQ4KKTuelZfk6D1drC8oXvSZIjNSQthMASBuAoq3FTDgdC5ax0tB
ZUy1KkXeDG7hgL7YmaTYv1Wq6a9NSb86WfiLvel4vELtHz2Nt3DA7TfB4+FP44ao3vYg4cY/p928
KIA+EHuR6eqk2tMr4OncNq38clEF14FTu1KASbuSNP7sRclZsxcNuLIrvcyQ

**Comment by legoboy0215** [comment] 2015-08-26 23:12
Duplicate of like 20 issues. This is when the plugin or server assumes the player is still online but he actually is not.

**Comment by pomee4** [comment] 2015-08-27 12:49
How can i solve it?

**Comment by SkygridRex** [comment] 2015-08-27 23:35
Remove all plugins by DarkGod

**Comment by legoboy0215** [comment] 2015-08-28 05:46
Maybe. This will be fixed I think.

**Comment by pomee4** [comment] 2015-08-28 09:28
I updated my pocketmine dev built to latest, now its a bit better, this error come after 3-4H of runung..
Btw i try to replace DarkGod's plugins but it would be great if i can use our own plugins. how can we fix tht in our plugins?

**Comment by Intyre** [comment] 2015-08-28 14:43
Please read the [contributing guide](https://github.com/PocketMine/PocketMine-MP/blob/master/CONTRIBUTING.md) before creating issues.

**Closed by Intyre** 2015-08-28 14:43 UTC
