### ISSUE TITLE
PEOPLE CAN'T ENTER IN MY SERVER WITHOUT LAN CONNECTION

### ISSUE THREAD

**Issue by Dhrhciebcy** [PocketMine/PocketMine-MP#4358] opened 2017-07-31 10:37 UTC
### Issue description
I start my server, it works fine. I try to enter in it in LAN and it works perfectly, but if I try to enter from another location my phone freezes on building terrain!!! My console doesn't report errors!!! I joined in the server with a LAN connected device and I saw that if I tried to connect with another device from its 4G Sim, it enter inside but it was freezed in "building terrain". Only one of my 4 devices has this problem and it's my most important device! Ports are open and my server results online, but anyone can enter. There isn't whitelist. Please help!!! :'(

### Steps to reproduce the issue
1. Start the server
2. Enter with a 4G Sim or a different Wi-Fi location

### OS and versions
* PocketMine-MP: most recents
* PHP: 7.0.3
* OS: Linux (Android 4.4.2, EMUI 3.0)
* Host Model: Huawei Honor 6 H06-L02

### Crashdump, backtrace or other files
* Everything works perfectly in the console! :(

**Comment by Johnmacrocraft** [comment] 2017-08-02 03:07
Perfect duplicate of pmmp/PocketMine-MP#1262

**Comment by Dhrhciebcy** [comment] 2017-08-02 06:01
Yes, I wrote it (#1262) because is very urgent for me! :(

**Comment by mire3212** [comment] 2017-08-19 16:11
@Dhrhciebcy If everything works when you're on the local LAN, and only fails when you connect externally, then your issue is very likely due to a NAT or Firewall issue.

**Comment by Dhrhciebcy** [comment] 2017-08-19 17:32
Interesting... 🤔
How can resolve this issue in your opinion? 🙏

P. S. I have the ports opened and, also if players can't enter "externally", the server results online

**Comment by aboese** [comment] 2017-09-16 15:44
Please learn about networking first prior to posting these questions. Try looking up ¨port forwarding¨. That might help.

**Comment by Dhrhciebcy** [comment] 2017-09-16 15:54
...maybe I was not clear. My server's ports are opened, people see that it's open but when they try to enter, minecraft freezes on "loading terrain". So probably it isn't a port forwarding problem in my opinion. 🤔

**Closed** 2017-12-31 11:00 UTC
