### ISSUE TITLE
Crafting problem via Windows 10 Edition

### ISSUE THREAD

**Issue by razorthiago** [PocketMine/PocketMine-MP#4028] opened 2016-03-07 19:13 UTC
### Issue description

Problem when you try to crafting an item by inventory or by crafting table via W10 Edition. iOS and Android operating normally.
### Steps to reproduce the issue

1. collect wood
2. try crafting Wood Planks
### OS and versions

- PocketMine-MP: PocketMine-MP 1.6dev 「[REDACTED]」 implementing API version 2.0.0 for Minecraft: PE v0.14.0.0 alpha (protocol version 45)
- PHP: 7.0.3
- OS: Windows 10
### Crashdump, backtrace or other files

```
Notice: Undefined offset: 0 in D:\PocketMine\src\pocketmine\Player.php on line 2579

Call Stack:
    0.0021     359544   1. {main}() D:\PocketMine\src\pocketmine\PocketMine.php:0
    0.2003     543848   2. pocketmine\Server->__construct() D:\PocketMine\src\pocketmine\PocketMine.php:464
    1.4639   14126752   3. pocketmine\Server->start() D:\PocketMine\src\pocketmine\Server.php:1652
    1.4779   14239096   4. pocketmine\Server->tickProcessor() D:\PocketMine\src\pocketmine\Server.php:2033
  140.7777   40860352   5. pocketmine\Server->tick() D:\PocketMine\src\pocketmine\Server.php:2153
  140.7777   40860352   6. pocketmine\network\Network->processInterfaces() D:\PocketMine\src\pocketmine\Server.php:2397
  140.7777   40860352   7. pocketmine\network\RakLibInterface->process() D:\PocketMine\src\pocketmine\network\Network.php:143
  140.7777   40860352   8. raklib\server\ServerHandler->handlePacket() D:\PocketMine\src\pocketmine\network\RakLibInterface.php:75
  140.7778   40860912   9. pocketmine\network\RakLibInterface->handleEncapsulated() D:\PocketMine\src\raklib\server\ServerHandler.php:92
  140.7779   40862320  10. pocketmine\Player->handleDataPacket() D:\PocketMine\src\pocketmine\network\RakLibInterface.php:136

[15:12:28] [RakLibServer thread/NOTICE]: Blocked 192.168.1.100 for 5 seconds
```

**Comment by thebigsmileXD** [comment] 2016-03-10 13:54
Maybe related to deepEquals.

**Comment by jbramburek** [comment] 2016-03-15 21:36
+1 - exactly the same issue on Windows 10

**Comment by egarland** [comment] 2016-03-19 19:17
Same problem.  Cant craft on Win10 edition.  
/src/pocketmine/Player__64bit.php on line 2579

**Comment by Delimer** [comment] 2016-03-27 19:10
its problem in win10 client

> I've captured the CraftEventPacket both on PE and W10E and found that W10E never sends what was being used to craft.
>I am afraid that this might be a client-side issue.
>The only way to fix is to ignore input items which will definitely make the server unsafe.

https://github.com/Nukkit/Nukkit/issues/576

**Comment by JackNoordhuis** [comment] 2016-03-29 05:26
Apparently MiNET works well, maybe have a look at that?

**Comment by Pub4Game** [comment] 2016-03-29 05:36
Hmm... Interesting

**Comment by thebigsmileXD** [comment] 2016-03-29 06:58
I dont think minet has a crafting manager

**Comment by Intyre** [comment] 2016-03-29 07:42
Please stop commenting unless you can give more information. Use the PacketLogger plugin, start capturing and try to narrow down the cause.

**Comment by thebigsmileXD** [comment] 2016-03-30 10:12
@Intyre i did that. The client sends the packet, but not the ingediants. (Also figured out that the win 10 drop bug is related to the crafting inventory in the players inventory. it always tries to drop all items of these slots.)

**Comment by extremeheat** [comment] 2016-04-03 23:44
A potential fix would be to keep track of items that are being picked up, and using them to figure out the ingredients used to craft the result.

**Comment by L3ice** [comment] 2016-04-09 20:56
Maybe 0.14.1 fixed the issue

**Comment by TheDeibo** [comment] 2016-04-09 21:00
@L3ice No, it hasn't. :(

@Intyre is this of any use to you? https://www.dropbox.com/s/2dsr4gy39vgnafy/thedeiboknows_-5838635226970660496-1459958641.log?dl=0

**Comment by thebigsmileXD** [comment] 2016-04-10 06:26
Nope

**Comment by thebigsmileXD** [comment] 2016-05-10 01:48
Remove "Mojang" Tag. @robske110 can you please tell the commit of the blackhunter or so which fixes it?

**Comment by robske110** [comment] 2016-05-10 04:58
https://gist.github.com/extremeheat/f1e9e0b8ca884727e6a3abfc7bfdc5a3

**Comment by dktapps** [comment] 2017-12-31 11:20
This has long since been fixed on PMMP's PocketMine-MP (versions of MCPE 1.2+).

**Closed by dktapps** 2017-12-31 11:20 UTC
Labels: Mojang
