### ISSUE TITLE
Some flower types cant be placed in creative but can be placed in survival 

### ISSUE THREAD

**Issue by mightysun99** [PocketMine/PocketMine-MP#2763] opened 2015-03-09 07:55 UTC
Every flower expect poppy and the dandelion cant be placed while the player is in creative.

**Comment by endercreep** [comment] 2015-03-09 22:57
i also have been experiencing this problem, i have found that while in the server, you are able to use /give while in survival to get the flowers. the double high flowers, such as; rose bushes, lilacs, double high grass, and peonies are  accessible as well, ALTHOUGH, they only show the bottom block of the flower. the second block is not shown when placed. 
![screenshot_2015-03-09-17-51-25](https://cloud.githubusercontent.com/assets/11398046/6566231/78f2c678-c685-11e4-9e12-9dda6d551d47.png)

**Comment by sekjun9878** [comment] 2015-03-21 11:17
Duplicate of #2768 as that issue is more broad in scope. Please continue discussion there.

**Closed by sekjun9878** 2015-03-21 11:17 UTC

**Comment by mightysun99** [comment] 2015-03-26 20:51
Whilst Rails, paintings, spawn eggs cant be placed in any gamemode flowers can be placed in survival but not creative.
