### ISSUE TITLE
op bug

### ISSUE THREAD

**Issue by advocaite** [PocketMine/PocketMine-MP#2553] opened 2015-01-20 09:27 UTC
If I op a player they can run any op command plugin or server wise, when I deop they still can run any command that is defaulted for ops or op only, untill they logout dc or kicked,Im not in control of the deop function and it should be that function which clears any and all op permissions based on player who was de opped, not a plugin that is a server command and when you deop them its ment to clear them there is no reason and its totally stupid of a plugin to have to listen for deop commands to reset permisions, I hope you understand now what im saying. please fix this security breach

**Comment by Striker209MPE** [comment] 2015-01-20 15:31
Interesting issue I believe

**Comment by iksaku** [comment] 2015-01-20 23:44
I confirm this bug... The server doesn't recalculate the permission nodes correctly

**Comment by Intyre** [comment] 2015-01-21 13:39
I can't confirm this bug... Tested with and without plugins. 
The plugin i used to test was PaintMyLawn.

I'll close this for now. But if you can give the steps to reproduce the issue and the cause is really PocketMine-MP then i'll reopen it.

**Closed by Intyre** 2015-01-21 13:39 UTC

**Comment by advocaite** [comment] 2015-01-26 13:12
basically get a plugin to have a command that is defaulted to op via the plugin.yml , run command, deop player, run command again. it will still allow you to run it.

**Comment by Intyre** [comment] 2015-01-26 13:26
Like i said i used PaintMyLawn plugin that has a default op command ``/paint``. 
Couldn't run that command without being op. 
Opped myself and it worked like expected. 
Deopped myself, tried the command but PocketMine told me that i didn't have permission to run it.
All that without disconnecting to the server.

Do you mind to give the name of the plugin you got problems with?

**Comment by advocaite** [comment] 2015-01-26 17:39
essentialsTP

**Comment by Intyre** [comment] 2015-01-26 18:28
EssentialsPE? That's weird because it just works. 
Command used was ``/getpos``
![proof](http://i.imgur.com/nAi9VIG.png)
