### ISSUE TITLE
FURNACE CRASHES GAME (CLIENT)

### ISSUE THREAD

**Issue by Caier** [PocketMine/PocketMine-MP#3814] opened 2015-12-28 12:49 UTC
When furnace is placed I can use it but when i disconnect from server and connect and try to open furnace it crashes whole game.

**Comment by elw124** [comment] 2016-01-03 21:44
Agreed.  I found this same issue.

**Comment by Jorti1** [comment] 2016-01-05 04:59
I also found that problem , maybe it is the PocketMine-MP.phar ??

I havent gotten bleeding phar 55 cause the website is down

**Comment by PEMapModder** [comment] 2016-01-05 08:53
@Jorti1 PocketMine newest updates are development builds, not bleeding builds.

**Comment by robske110** [comment] 2016-01-05 08:56
And where can we get them?

**Comment by PEMapModder** [comment] 2016-01-05 09:17
http://www.pocketmine.net/api/?channel=development

> `"alternate_download_url": "http://cdn.pocketmine.net/api/update-development.phar"`

**Comment by robske110** [comment] 2016-01-05 10:06
Because jenins is still down :(

**Comment by PEMapModder** [comment] 2016-01-05 12:48
@robske110 that has nothing to do with Jenkins...

**Comment by robske110** [comment] 2016-01-05 12:50
http://jenkins.pocketmine.net/job/PocketMine-MP/1266/",?

**Comment by PEMapModder** [comment] 2016-02-19 10:08
Duplicate of #3749

**Closed by PEMapModder** 2016-02-19 10:08 UTC
