### ISSUE TITLE
Blocks Regenerate while Mining stone

### ISSUE THREAD

**Issue by fouad922** [PocketMine/PocketMine-MP#2836] opened 2015-04-06 18:50 UTC
Ive been seeing this problom in dev stable and soft. The blocks only regenerate while mining stone.
What could be causing this problem. And im pretty sure my network is not the problem. I have no plugins.

**Comment by alejandroliu** [comment] 2015-04-09 10:39
Do you have spawn protection?  And does it happen in the spawn area?

Does it happen only to stone blocks?

**Comment by fouad922** [comment] 2015-04-10 08:32
Spawn Protection is disabled and it happens everywhere mostly noticed it with just stone.

**Comment by WhiteWolfOwner** [comment] 2015-04-17 00:01
Go to this link... I posted about this problem... Might help!
https://github.com/PocketMine/PocketMine-MP/issues/2894

Thanks,
WhiteWolfOwner

**Comment by sekjun9878** [comment] 2015-05-23 12:48
Duplicate of #2842, please refer all future replies to #2842 instead. Thanks!

**Closed by sekjun9878** 2015-05-23 12:48 UTC
