### ISSUE TITLE
Arrow doesn't shoot when player jumps

### ISSUE THREAD

**Issue by CaptainKenji17** [PocketMine/PocketMine-MP#3913] opened 2016-01-31 08:24 UTC
well I found the causes of this ;)

it dont shoot arrow when you jump and shoot

**Comment by PEMapModder** [comment] 2016-01-31 10:31
I am experiencing deja vu reading this. Is this duplicated?

**Comment by PocketKiller** [comment] 2016-01-31 12:57
confirmed.

**Comment by thebigsmileXD** [comment] 2016-03-10 13:55
#4029

**Comment by GlitchPlayer** [comment] 2016-03-19 13:57
This issue existed on my server.

**Comment by GlitchPlayer** [comment] 2016-04-05 09:50
Also when sneaking, you cant shoot also.

**Comment by PrimusLV** [comment] 2016-04-16 12:12
After player jumps or sneaks data flag ```DATA_FLAG_ACTION``` is removed

**Comment by thebigsmileXD** [comment] 2016-04-17 09:52
So a client issue?

**Comment by CaptainKenji17** [comment] 2016-04-17 10:32
No its PocketMine issue

**Comment by dktapps** [comment] 2017-12-31 11:24
This has long since been fixed on PMMP's PocketMine-MP.

**Closed by dktapps** 2017-12-31 11:24 UTC
Labels: C: Gameplay, Reproduced
