### ISSUE TITLE
waterfall into still water creates air pockets in the still water when stopped

### ISSUE THREAD

**Issue by unerds** [PocketMine/PocketMine-MP#2625] opened 2015-02-10 07:29 UTC
made a waterfall into a lake, and when i blocked the waterfall, the still water in the lake seems to have been overwritten by the falling water, and when the falling water stopped flowing, it just left air.

i hope i'm explaining that well enough.

cheers

**Comment by jingz2007** [comment] 2015-06-06 15:39
That happens to me even on a local minecraft pocket edition world.

**Comment by PEMapModder** [comment] 2015-06-06 16:27
Good. Minecraft is now more realistic. :)

**Comment by JoahDave** [comment] 2015-06-06 23:23
@PEMapModder :)

**Comment by dktapps** [comment] 2017-12-31 11:38
Duplicate of #2584

**Closed by dktapps** 2017-12-31 11:38 UTC
