### ISSUE TITLE
Unable to Break Redstone Ore

### ISSUE THREAD

**Issue by Kanonen** [PocketMine/PocketMine-MP#3325] opened 2015-07-28 14:34 UTC
<b>Pocketmine-MP Build #1258</b>
When attempting to break a redstone ore block with an iron pickaxe, diamond pickaxe, and stone shovel: the redstone ore will disappear for a split second when it is supposed to have 'broken', but then immediately re-appears. No redstone is dropped.

<i>Note: Block I'm attempting to break is "Glowing Redstone Ore"</i>

**Comment by sithsiri** [comment] 2015-08-08 19:28
This is probably lag.

**Comment by JoahDave** [comment] 2015-08-09 00:05
Reproduced!
@sithsiri This is not lag.

**Comment by sithsiri** [comment] 2015-08-09 00:08
Okay. I don't go mining on my server, so I wouldn't know...

**Comment by iksaku** [comment] 2015-08-09 07:01
@sithsiri Then don't fire *useless* solutions

**Comment by dktapps** [comment] 2017-12-31 11:33
This has long since been fixed on PMMP's PocketMine-MP. (Hardness bug, it also existed with several other blocks including netherrack.)

**Closed by dktapps** 2017-12-31 11:33 UTC
