### ISSUE TITLE
player movement rubber banding while walking on slabs and stairs

### ISSUE THREAD

**Issue by unerds** [PocketMine/PocketMine-MP#2604] opened 2015-02-03 23:56 UTC
console will also populate with 'player moved wrongly' messages while players are skittering along.

i saw that this one was reported and closed already, but it seems to be still occurring as of dev956

**Comment by Darkrift411** [comment] 2015-02-04 01:04
Verified this with any half blocks.

**Comment by MobileCrafter** [comment] 2015-02-09 08:57
Also it sometimes happen on full blocks when you move along.
Maybe because of the grass, I dont know.

**Comment by Creeperface01** [comment] 2015-02-09 20:03
and when this will be fixed?

**Comment by unerds** [comment] 2015-02-10 07:15
also possibly worth noting, this doesn't seem to effect players in creative mode, so it may be related to the -no flight- check - 

it seems as though jumping up stairs and such really helps to minimize the effect which would otherwise just rubberband until you get off the half block.

**Comment by Darklord505** [comment] 2015-02-15 18:29
Well it's a type of glitch and I encountered it before and it's sort-of annoying.

**Comment by unerds** [comment] 2015-02-23 06:22
this issue is 10x worse now on build 965.

can't even get on a slab.

**Comment by Creeperface01** [comment] 2015-03-14 14:53
yes how can I fix it?

**Comment by Midnight-Shadow** [comment] 2015-03-28 23:27
Confirmed. No ideas how to fix it. Don't program php.

**Comment by WhiteWolfOwner** [comment] 2015-04-16 23:56
Go to this link... I posted about it.
Same issue but different name...
https://github.com/PocketMine/PocketMine-MP/issues/2778

**Comment by JoahDave** [comment] 2015-04-28 03:16
Confirmed. Quite annoying. I was able to clip through a half slab when the server teleported me abound when I "moved wrongly"

**Comment by shoghicp** [comment] 2015-04-28 07:52
Please do not comment on old issues. This has been fixed on the newest version.

**Closed by shoghicp** 2015-04-28 07:52 UTC

**Comment by isoz** [comment] 2016-01-18 02:25
Lol fixed
