### ISSUE TITLE
Parameter miss in Level.php line 1230

### ISSUE THREAD

**Issue by MagicDroidX** [PocketMine/PocketMine-MP#3527] opened 2015-09-26 07:09 UTC
THIS IS NOT A CRASH DUMP NOR A PASTE OF EXCEPTION or ERROR

On line 1230 in Level.php (master branch)
max() missing the 2rd parameter but we have never seen an error, so light level is always bigger than 15.
I think the light level's range is 0-15.
So i wonder if this is a calculation error and if this will cause light bug?

**Comment by 202831820** [comment] 2015-09-26 10:10
No,I debugged the server locally I didn't see any call to this method internally in PocketMine. Maybe it's for API calls.

PM代码里面都没调用这个方法啊。

**Comment by MagicDroidX** [comment] 2015-09-26 10:15
Ok. But that might cause error.

**Comment by PEMapModder** [comment] 2015-09-26 10:37
According to [//php.net/max](PHP manual):

> ```php
> mixed max ( array $values )
> ```
>
> If the first and only parameter is an array, max() returns the highest value in that array. 

PocketMine is using the `max` function to find out the largest number returned by `$chunk->getBlockLight()`. This does not cause any errors nor results in any bugs or unintended behaviour.

**Comment by MagicDroidX** [comment] 2015-09-26 10:43
according to the interface, it returns an int not an array :/

**Comment by 202831820** [comment] 2015-09-26 11:49
But getBlockLight didn't return any array indeed.   crash may be occurred with message: "
Warning: max(): When only one parameter is given, it must be an array
"when this line reached.

no error because this line will never be reached currently.

**Comment by MagicDroidX** [comment] 2015-09-26 12:12
But this is a part of API I think, and can reach this error.

**Comment by PEMapModder** [comment] 2016-02-14 06:10
The PHP `max()` function also accepts an array as parameter. `max($array)` does the same thing as `max(...$array)`.

**Comment by dktapps** [comment] 2017-12-31 11:27
This has long since been fixed on PMMP's PocketMine-MP.

**Closed by dktapps** 2017-12-31 11:27 UTC
