### ISSUE TITLE
Lake generation

### ISSUE THREAD

**Issue by James76931** [PocketMine/PocketMine-MP#3818] opened 2015-12-29 00:20 UTC
Lakes will generate with grass below them instead of dirt now and then. Not all the time, just now and then.

**Comment by James76931** [comment] 2015-12-29 09:53
Never mind, it is all the time and it also includes the sea - not just lakes.

**Comment by PEMapModder** [comment] 2015-12-29 09:55
Duplicate of #3173

**Comment by James76931** [comment] 2015-12-29 09:58
Whoops, didn't notice that :P

**Comment by PEMapModder** [comment] 2015-12-29 12:36
Close the issue.

**Closed** 2015-12-29 13:28 UTC
