### ISSUE TITLE
logged out due to Outdated server! [v0.15.0.0 alpha]

### ISSUE THREAD

**Issue by fableman73** [PocketMine/PocketMine-MP#4262] opened 2016-08-14 15:08 UTC
I think App store updated my kidz minecraft client and now they can't access my server :(

Running Raspberry Pi
I have tried to:
wget -q -O - http://get.pocketmine.net/ | bash -s – -v development
and PocketMine-MP_1.6dev-27_ef8227a0_API-2.0.0.phar PocketMine-MP.phar

Still **logged out due to Outdated server!**

See logfile:

@minecraft:~ $ ./start.sh
[14:28:13] [Server thread/INFO]: Loading pocketmine.yml...
[14:28:13] [Server thread/INFO]: Loading server properties...
[14:28:13] [Server thread/INFO]: Selected English (eng) as the base language
[14:28:13] [Server thread/INFO]: Starting Minecraft: PE server version v0.15.0.0 alpha
[14:28:14] [Server thread/INFO]: Starting remote control listener
[14:28:14] [Server thread/INFO]: RCON running on 0.0.0.0:19132
[14:28:14] [Server thread/INFO]: Opening server on 0.0.0.0:19132
[14:28:14] [Server thread/INFO]: This server is running PocketMine-MP version 1.6dev "[REDACTED]" (API 2.0.0)
[14:28:14] [Server thread/INFO]: PocketMine-MP is distributed under the LGPL License
[14:28:14] [Server thread/INFO]: Loading recipes...
[14:28:15] [Server thread/INFO]: Loading SpawnWithItems v2.1
[14:28:15] [Server thread/INFO]: [SpawnWithItems] Loading SpawnWithItems v2.0 by LDX...
[14:28:15] [Server thread/INFO]: Preparing level "world"
[14:28:15] [Server thread/INFO]: Enabling SpawnWithItems v2.1
[14:28:15] [Server thread/INFO]: [SpawnWithItems] Enabling SpawnWithItems...
[14:28:16] [Server thread/INFO]: Starting GS4 status listener
[14:28:16] [Server thread/INFO]: Setting query port to 19132
[14:28:16] [Server thread/INFO]: Query running on 0.0.0.0:19132
[14:28:16] [Server thread/INFO]: Default game type: Survival Mode
[14:28:16] [Server thread/INFO]: Done (2.607s)! For help, type "help" or "?"
**[14:29:50] [Server thread/INFO]: Alex[/10.0.100.236:19132] logged out due to Outdated server!
[14:29:59] [Server thread/INFO]: Alex[/10.0.100.236:19132] logged out due to Outdated server!
[14:30:29] [Server thread/INFO]: Alex[/10.0.100.236:19132] logged out due to Outdated server!**

**Comment by robske110** [comment] 2016-08-14 15:18
Use the latest version of pocketmine

**Comment by robske110** [comment] 2016-08-14 15:18
https://bintray.com/pocketmine/PocketMine/PocketMine-MP-phar#files

Replace your PocketMine.phar with the newest phar there.

**Comment by fableman73** [comment] 2016-08-14 15:27
If you read my message you can see I have the latest version installed.

**Comment by fableman73** [comment] 2016-08-14 15:29
I guess Minecraft PE will stop for more players then just apple users after theyt push out the changes of there client to Android and soo on.

**Comment by GlitchPlayer** [comment] 2016-08-14 15:31
The lastest version from app store
0.15.6

Pocketmine version
0.15.0

Unfornately, no

**Comment by fableman73** [comment] 2016-08-14 15:34
all worked fine before the client update on the ipad a few days ago.

I guess they changed something in the protocol, and PocketMine need to be updated to a newer version.

**Comment by robske110** [comment] 2016-08-14 15:54
well, weird. I din't notice any changes in 0.15.6

**Comment by robske110** [comment] 2016-08-14 15:57
You  can either ...
edit the pocketmine source to accept protocol 81. (If you need help here feel free to contact me)
or use https://github.com/ClearSkyTeam/ClearSky (Just replace your PocketMine-MP.phar with http://robskebueba.no-ip.biz/CSPhar.php?type=1&branch=php7 ).
And by the way: This project is unofficially dead. We do not know if this repo will receive a commit EVER again.

**Comment by GlitchPlayer** [comment] 2016-08-14 16:08
0.15.4 had protocol changes

**Comment by robske110** [comment] 2016-08-14 16:08
i know..

**Comment by ZackLuvsGamez** [comment] 2016-08-15 13:00
how do i get the 0.15 phar with php7?

**Comment by robske110** [comment] 2016-08-15 13:04
http://robskebueba.no-ip.biz/CSPhar.php?type=1&branch=php7
there or somewhere on genisys
0.15.4+ is currently not supported by pockemtine

**Comment by fableman73** [comment] 2016-08-15 21:52
Thank you robske110. ClearSky worked perfect. (even if it is a dev version at this point with this fix)
I hade to use the php hardcoded for ARM to get the php7 working on Raspberry Pi from this project.

**Comment by Survingo** [comment] 2016-08-16 09:38
@robske110 There's a much better way to update the version instead of advertising.
Because 0.15.4 and 0.15.6 had no protocol changes (@GlitchPlayer) can you update PocketMine by yourself by google searching "survingo update 0.15.4.0 0.15.6 site:forums.pocketmine.net"

**Comment by GlitchPlayer** [comment] 2016-08-16 09:53
@Survingo  Lel, I do not use pocketmine anymore. Due to the fact pocketmine is dead. Genisys is more advanced and flexible. Also, 0.15.4 has protocol changes is that new skin pack are added.

**Comment by robske110** [comment] 2016-08-16 09:59
I told them that they can change the protocol version in Info.php. You're advertising for searching 'survingoM

**Comment by Survingo** [comment] 2016-08-16 10:01
"the fact pocketmine is dead"... Who said that it is an fact? Well, if you mean. Most community guys inclusive me mean that it is an fact pocketmine is alive. Everyone has his side ;)
@robske110 xD

**Comment by robske110** [comment] 2016-08-16 10:02
Quoting me:
>And by the way: This project may be unofficially dead. We do not know if this repo will receive a commit EVER again.

**Comment by GlitchPlayer** [comment] 2016-08-16 10:03
@Survingo Well, it's a fact for me. Since you said "Everyone has his side ;)"

**Comment by GlitchPlayer** [comment] 2016-08-16 10:05
Also, pocketmine has missing features such as Mob AI. Many plugins will soon make this to provide player's satisfaction. Not only that, Many servers now switched into many third-party server hosting. LEET too.

**Comment by Survingo** [comment] 2016-08-16 10:15
That's what forks do

No server network is using PocketMine nowadays

**Comment by GlitchPlayer** [comment] 2016-08-16 10:19
Yup. I recommend you to use fork for a while. Pocketmine is recruiting new members for while

**Comment by ZackLuvsGamez** [comment] 2016-08-16 16:47
Is the phar downloadable on Android?

**Comment by craigbrian** [comment] 2016-08-30 05:36
Wrong v15.0.4 is available and it works I tried it on my Multiworld SkyBlock Server
https://www.mediafire.com/download/97aun4agqru4f6n
https://app.box.com/s/833f28v50pu5tx4st0r9t7ygt8hdgge3

**Comment by archie426** [comment] 2016-08-31 09:09
Bump it by doing the instructions supplied by Survingo at https://forums.pocketmine.net/threads/version-issues.18015/

**Comment by archie426** [comment] 2016-08-31 09:11
robske, r u from ClearSky because ur kinda advertising

**Comment by dktapps** [comment] 2016-08-31 09:53
@archie426 actually it kind of _is_ dead. Confirmed.

**Comment by archie426** [comment] 2016-08-31 12:10
Yes tou do have a point. However it is not completely dead

**Comment by robske110** [comment] 2016-08-31 12:49
I define this repo as dead. No, actually i define exactly the commits here as dead. We'll not see any in any near time.

**Comment by richardpickett** [comment] 2016-08-31 12:57
A couple months ago I thought I'd setup a minecraft server for my daughter
and I to build on. I went with PocketMine, looked like it had the most
features, wide range of plugins, etc.

https://github.com/PocketMine/PocketMine-MP/graphs/contributors

This page bothered me a little, but I took the time to download and set it
up anyway. Another problem was the main instructions from the pocketmine
website didn't give you a working server. I had to keep searching around
for different install instructions before I got it to work. That means just
to use the product the user has to figure it out - the product owner
doesn't care that much if you can use it or not.

Anyway, back to why that github page bothered me - that first graph shows a
lot of initial work and then it tapers off to just about nothing. The "a
lot of initial work" is normal, that's when you're first building something
out and you've got that fever to get something done. But the "tapers off to
just about nothing" is definitely not normal, that's a sign of a dead
project.

Especially when you think about something as critical as the current issue
discussed on this thread - a simple change to allow a higher protocol
number be accepted on the server. This simple change can't get addressed in
2 weeks, and the only workarounds presented are pulling the change needed
from somewhere else.

-> That means the owner of the product really just doesn't care if you can
use it or not. <-

As great as pocketmine may have been, that statement sums up it's current
state.

It seems that although Shoghi didn't intend for his job change to affect
PM, it actually has. His last greatest contribution seems to be the move to
php7, which was certainly a great feat, but I can't find anything
significant after that upgrade. And he rarely, if ever, logs into his own
product's forum. That doesn't sound like a lot of commitment. I'm not
putting him down - I'm just observing. Maybe he's had something else in
life come up that we don't know. Got married, got sick (hope not). But
whatever the reason is, the product owner hasn't been able to dedicate his
time.

For PM to survive, it would take a couple devs who catch the fever and make
regular contributions to it. At a minimum I'd expect to see someone at
least fix "logged out due to Outdated server" within a day, two at the most.

I'm not going to advertise for Genisys, but since it was one of the other
platforms brought up, I figure I should post it's "work history":

https://github.com/iTXTech/Genisys/graphs/contributors

You can see it's still quite active. And the other one mentioned was
clearsky:

https://github.com/ClearSkyTeam/ClearSky/graphs/contributors

Not as much as Genisys, but it's still being actively developed.

I'll probably move off of PM, this obviously isn't working. Not sure which
one I'll move too - that's why I can safely say I'm not advertising
anything.





Thanks, be blessed,

Richard W. Pickett, Jr.
President, CSR Technologies .com, Inc.

**Comment by dktapps** [comment] 2016-08-31 13:17
@shoghicp has the only set of keys to PocketMine. We're locked out of the house and nobody else can let people in. Sad to say ...

**Comment by archie426** [comment] 2016-09-01 07:01
Goodpoint

**Comment by archie426** [comment] 2016-09-01 07:05
Richard, PM is not like other companies. It is not all about the business for the founders and devs. And this goes for the other forks as well. They do not do it for a prophet. You should make sure you understand the project clearly before you jump into things. I made that mistake once. So maybe your (how can I put it) Right-wing opinion of a company does not apply to Pocketmine or its' forks. Sorry if i sound rude.

**Comment by archie426** [comment] 2016-09-01 07:17
Richard, if ur going to complain why dont you make commits? Also, I said earlier the outdated server issue can be fixed by editing the .phar. You obviously do not know how hard it is to code. Pocketmine (and its forks) are not for profit. They do not want just the money. They just want to make a great server software that people will use and contribute to. So your right-wing view of a company does not apply to pocketmine (and it s forks)

**Comment by GlitchPlayer** [comment] 2016-09-01 08:48
Guys, for any reason. @robske110 is just not advertising. There are other forks in there that are updated in all mcpe versions. @archie426 No, the staffs are not inactive. They left the project. Making PM died. You are right, people can just ask to other persons. But what if they gave you a malicious code injected to the modified PM? You can't trust anyone on the internet. Trust on people who gives true work.

As you see on the forums, the one staff on PM announce that they are recruiting new people. Which means the old staffs left. Your wrong. Please read before making any reasons.

@shoghicp promised us he will still work on PM. But as @Intyre said, "I have no contact with @shoghicp with many months" So, we don't know when he will come back.

**Comment by robske110** [comment] 2016-09-01 11:14
And please take in consideration that if shoghicp isn't careful enough Mojang may DMCA PM [Due to him accidently copying variable names here or such minimalaties.]. And mojang is desperate to do so i think, we're a real issue for REALMS. (Well as i think about this maybe there are some humans at mojang, because they did not (yet) remove the external server feature).

**Comment by GlitchPlayer** [comment] 2016-09-07 03:59
@robske10 wow.. your right... Mojang has need to release a official software for servers now.

**Comment by DiegoGTRatty** [comment] 2016-09-08 19:12
Mojang became EA.

Why do you think Realms cost money?

**Comment by Tee7even** [comment] 2016-09-08 23:15
>Why do you think Realms cost money?

Ehrm, maybe because it does..?

**Comment by GlitchPlayer** [comment] 2016-09-09 14:15
@DiegoGTRatty because it's hosted online and located at mojang?

**Comment by richardpickett** [comment] 2016-09-09 14:48
(archie426)
Richard, PM is not like other companies.


Who said anything about companies? I said "product". Shoghi is a producer.
He's produced something. It's called PocketMine. The thing produced is
called a product.

It is not all about the business for the founders and devs.

Didn't say it was. *I'm just pointing out it's no longer supported and no
one should have any expectation of future support from this product.*


And this goes for the other forks as well. They do not do it for a prophet.
You should make sure you understand the project clearly before you jump
into things. I made that mistake once. So maybe your (how can I put it)
Right-wing opinion of a company does not apply to Pocketmine or its' forks.

Right wing?

Company?

lol.

You're the only one talking about money, companies, profit (well,
technically you mention prophet, which is kinda funny). I didn't even talk
in these terms.


Sorry if i sound rude.

You don't sound rude. You sound ignorant. I write "Aaaaaaaa" and you argue
"But Richard, 'Bbbbbbbbbb' is so wrong...."

Pay attention.



(archie426)
Richard, if ur going to complain why dont you make commits?

Where is the complaint? I only point out PM is no longer supported.


Also, I said earlier the outdated server issue can be fixed by editing the
.phar.

So easy that the Product Owner can't do it. That means he doesn't care if
it's supported any more. That's all I'm saying.


You obviously do not know how hard it is to code.

You obviously know nothing about me.


 Pocketmine (and its forks) are not for profit.

(sigh) "profit" again. I didn't say anything about profit...


 They do not want just the money.

or money.


They just want to make a great server software that people will use and
contribute to.

It may be true that they "want" to. But what we want to do and what we do
are two different things. As you can see. What has been accomplished is a
great (or was a great) server software that people can contribute to. The
"will use" part has faded already.


So your right-wing view of a company does not apply to pocketmine (and it s
forks)


What you really mean is your interpretation of what I've said into some
right-wing statement about companies and profit doesn't apply to PocketMine.

Everything I've actually said before running it through your interpretation
layer is perfectly true. PM isn't being supported any more. Unless some
devs pick it up and run with it it's going to stay dead.

The next thing that will drop off will be the downloads. Then finally the
users.

Of course there will always be that small group of users that will keep
editing phar files and telling others how to do the same, so they can all
continue to use something that has no new features while other similar
products continue to improve and implement new features all around them.


Thanks, be blessed,

Richard W. Pickett, Jr.
President, CSR Technologies .com, Inc.

**Comment by robske110** [comment] 2016-09-09 14:59
Good explanation @richardpickett . And this repo is really dead, Intyre himself has pointed that out (not publicly though).
I do not know if shoghicp plans to do ANYTHING. If I would be him and I created a project which has got the attention of over 1000 (probably 10000) I would NEVER throw it away. I may come to a point were i can't contribute to it anymore. But I would give the keys to it to someone who i trust and let him continue is. We're locked out of this Project.

**Comment by jojoe77777** [comment] 2016-09-09 15:03
> over 1000 (probably 10000) 

Look at the plugin download counts on PocketMine Forums...

**Comment by mhsjlw** [comment] 2016-09-09 20:59
@richardpickett, 'finding developers' is not nearly as easy as it sounds. Not only that, but these developers will not 'catch the fever' mostly because of how horribly written and designed PocketMine is. The PocketMine community is very divided in every sense of the word so you're just going to have to take a side of Genisys/ClearSky if you want a working server.

**Comment by robske110** [comment] 2016-09-09 21:28
The biggest design flaw is even starting to design a game server on PHP.

**Comment by DiegoGTRatty** [comment] 2016-09-13 18:58
@GlitchPlayer AND consider that those servers are owned by Microsoft...

**Comment by DiegoGTRatty** [comment] 2016-09-13 19:01
@richardpickett 

PocketMine is like Need For Speed: World.

It certainly died, but enough support can "revive the dead".

**Comment by LestaD** [comment] 2016-10-11 22:30
When PM will update to v0.15.90?

**Comment by richardpickett** [comment] 2016-10-11 22:37
Everyone that could answer that question were all holding their breath
waiting for the update.

They've all died and won't be answering you.

**Comment by Survingo** [comment] 2016-10-11 22:52
This repo won't update especially PocketMine has a new [GitHub group](https://github.com/pmmp). Also wait until the original 0.16.0 will release and look again

**Comment by robske110** [comment] 2016-10-12 11:04
@richardpickett actually, PM has begun it's rise again. 
Almost all original PM memebers are there, except shoghicp of course.
https://github.com/pmmp/PocketMine-MP

**Closed** 2017-12-31 11:13 UTC
