### ISSUE TITLE
Crash when carpet, cake, or cactus stacked too high

### ISSUE THREAD

**Issue by Lucario2** [PocketMine/PocketMine-MP#3366] opened 2015-08-10 23:51 UTC
PocketMine-MP Crash Dump Mon Aug 10 18:29:10 ACT 2015

Error: Maximum function nesting level of '100' reached, aborting!
File: /src/pocketmine/event/Event
Line: 54
Type: E_ERROR

Code:
[45] final public function getEventName(){
[46] return $this->eventName === \null ? \get_class($this) : $this->eventName;
[47] }
[48]
[49] /**
[50] * @return bool
[51] *
[52] * @throws \BadMethodCallException
[53] /
[54] public function isCancelled(){
[55] if(!($this instanceof Cancellable)){
[56] throw new \BadMethodCallException("Event is not Cancellable");
[57] }
[58]
[59] /* @var Event $this /
[60] return $this->isCancelled === \true;
[61] }
[62]
[63] /*
[64] * @param bool $value

Backtrace:
#0 /src/pocketmine/Server__32bit(0): pocketmine\Server->crashDump()
#1 /src/pocketmine/plugin/PluginManager(673): pocketmine\plugin\RegisteredListener->callEvent()
#2 /src/pocketmine/Player__32bit(910): pocketmine\plugin\PluginManager->callEvent()
#3 /src/pocketmine/Server__32bit(1897): pocketmine\Player->dataPacket()
#4 /src/pocketmine/level/Level__32bit(848): pocketmine\Server::broadcastPacket()
#5 /src/pocketmine/level/Level__32bit(1409): pocketmine\level\Level->sendBlocks()
#6 /src/pocketmine/block/Block(571): pocketmine\level\Level->setBlock()
#7 /src/pocketmine/level/Level__32bit(1561): pocketmine\block\Block->onBreak()
#8 /src/pocketmine/block/Carpet(89): pocketmine\level\Level->useBreakOn()
#9 /src/pocketmine/level/Level__32bit(1019): pocketmine\block\Carpet->onUpdate()
#10 /src/pocketmine/level/Level__32bit(1434): pocketmine\level\Level->updateAround()
#11 /src/pocketmine/block/Block(571): pocketmine\level\Level->setBlock()
#12 /src/pocketmine/level/Level__32bit(1561): pocketmine\block\Block->onBreak()
#13 /src/pocketmine/block/Carpet(89): pocketmine\level\Level->useBreakOn()
#14 /src/pocketmine/level/Level__32bit(1019): pocketmine\block\Carpet->onUpdate()
#15 /src/pocketmine/level/Level__32bit(1434): pocketmine\level\Level->updateAround()
#16 /src/pocketmine/block/Block(571): pocketmine\level\Level->setBlock()
#17 /src/pocketmine/level/Level__32bit(1561): pocketmine\block\Block->onBreak()
#18 /src/pocketmine/block/Carpet(89): pocketmine\level\Level->useBreakOn()
#19 /src/pocketmine/level/Level__32bit(1019): pocketmine\block\Carpet->onUpdate()
#20 /src/pocketmine/level/Level__32bit(1434): pocketmine\level\Level->updateAround()
#21 /src/pocketmine/block/Block(571): pocketmine\level\Level->setBlock()
#22 /src/pocketmine/level/Level__32bit(1561): pocketmine\block\Block->onBreak()
#23 /src/pocketmine/block/Carpet(89): pocketmine\level\Level->useBreakOn()
#24 /src/pocketmine/level/Level__32bit(1019): pocketmine\block\Carpet->onUpdate()
#25 /src/pocketmine/level/Level__32bit(1434): pocketmine\level\Level->updateAround()
#26 /src/pocketmine/block/Block(571): pocketmine\level\Level->setBlock()
#27 /src/pocketmine/level/Level__32bit(1561): pocketmine\block\Block->onBreak()
#28 /src/pocketmine/block/Carpet(89): pocketmine\level\Level->useBreakOn()
#29 /src/pocketmine/level/Level__32bit(1019): pocketmine\block\Carpet->onUpdate()
#30 /src/pocketmine/level/Level__32bit(1434): pocketmine\level\Level->updateAround()
#31 /src/pocketmine/block/Block(571): pocketmine\level\Level->setBlock()
#32 /src/pocketmine/level/Level__32bit(1561): pocketmine\block\Block->onBreak()
#33 /src/pocketmine/block/Carpet(89): pocketmine\level\Level->useBreakOn()
#34 /src/pocketmine/level/Level__32bit(1019): pocketmine\block\Carpet->onUpdate()
#35 /src/pocketmine/level/Level__32bit(1434): pocketmine\level\Level->updateAround()
#36 /src/pocketmine/block/Block(571): pocketmine\level\Level->setBlock()
#37 /src/pocketmine/level/Level__32bit(1561): pocketmine\block\Block->onBreak()
#38 /src/pocketmine/block/Carpet(89): pocketmine\level\Level->useBreakOn()
#39 /src/pocketmine/level/Level__32bit(1019): pocketmine\block\Carpet->onUpdate()
#40 /src/pocketmine/level/Level__32bit(1434): pocketmine\level\Level->updateAround()
#41 /src/pocketmine/block/Block(571): pocketmine\level\Level->setBlock()
#42 /src/pocketmine/level/Level__32bit(1561): pocketmine\block\Block->onBreak()
#43 /src/pocketmine/block/Carpet(89): pocketmine\level\Level->useBreakOn()
#44 /src/pocketmine/level/Level__32bit(1019): pocketmine\block\Carpet->onUpdate()
#45 /src/pocketmine/level/Level__32bit(1434): pocketmine\level\Level->updateAround()
#46 /src/pocketmine/block/Block(571): pocketmine\level\Level->setBlock()
#47 /src/pocketmine/level/Level__32bit(1561): pocketmine\block\Block->onBreak()
#48 /src/pocketmine/block/Carpet(89): pocketmine\level\Level->useBreakOn()
#49 /src/pocketmine/level/Level__32bit(1019): pocketmine\block\Carpet->onUpdate()
#50 /src/pocketmine/level/Level__32bit(1434): pocketmine\level\Level->updateAround()
#51 /src/pocketmine/block/Block(571): pocketmine\level\Level->setBlock()
#52 /src/pocketmine/level/Level__32bit(1561): pocketmine\block\Block->onBreak()
#53 /src/pocketmine/block/Carpet(89): pocketmine\level\Level->useBreakOn()
#54 /src/pocketmine/level/Level__32bit(1019): pocketmine\block\Carpet->onUpdate()
#55 /src/pocketmine/level/Level__32bit(1434): pocketmine\level\Level->updateAround()
#56 /src/pocketmine/block/Block(571): pocketmine\level\Level->setBlock()
#57 /src/pocketmine/level/Level__32bit(1561): pocketmine\block\Block->onBreak()
#58 /src/pocketmine/block/Carpet(89): pocketmine\level\Level->useBreakOn()
#59 /src/pocketmine/level/Level__32bit(1019): pocketmine\block\Carpet->onUpdate()
#60 /src/pocketmine/level/Level__32bit(1434): pocketmine\level\Level->updateAround()
#61 /src/pocketmine/block/Block(571): pocketmine\level\Level->setBlock()
#62 /src/pocketmine/level/Level__32bit(1561): pocketmine\block\Block->onBreak()
#63 /src/pocketmine/block/Carpet(89): pocketmine\level\Level->useBreakOn()
#64 /src/pocketmine/level/Level__32bit(1019): pocketmine\block\Carpet->onUpdate()
#65 /src/pocketmine/level/Level__32bit(1434): pocketmine\level\Level->updateAround()
#66 /src/pocketmine/block/Block(571): pocketmine\level\Level->setBlock()
#67 /src/pocketmine/level/Level__32bit(1561): pocketmine\block\Block->onBreak()
#68 /src/pocketmine/block/Carpet(89): pocketmine\level\Level->useBreakOn()
#69 /src/pocketmine/level/Level__32bit(1019): pocketmine\block\Carpet->onUpdate()
#70 /src/pocketmine/level/Level__32bit(1434): pocketmine\level\Level->updateAround()
#71 /src/pocketmine/block/Block(571): pocketmine\level\Level->setBlock()
#72 /src/pocketmine/level/Level__32bit(1561): pocketmine\block\Block->onBreak()
#73 /src/pocketmine/block/Carpet(89): pocketmine\level\Level->useBreakOn()
#74 /src/pocketmine/level/Level__32bit(1019): pocketmine\block\Carpet->onUpdate()
#75 /src/pocketmine/level/Level__32bit(1434): pocketmine\level\Level->updateAround()
#76 /src/pocketmine/block/Block(571): pocketmine\level\Level->setBlock()
#77 /src/pocketmine/level/Level__32bit(1561): pocketmine\block\Block->onBreak()
#78 /src/pocketmine/block/Carpet(89): pocketmine\level\Level->useBreakOn()
#79 /src/pocketmine/level/Level__32bit(1019): pocketmine\block\Carpet->onUpdate()
#80 /src/pocketmine/level/Level__32bit(1434): pocketmine\level\Level->updateAround()
#81 /src/pocketmine/block/Block(571): pocketmine\level\Level->setBlock()
#82 /src/pocketmine/level/Level__32bit(1561): pocketmine\block\Block->onBreak()
#83 /src/pocketmine/block/Carpet(89): pocketmine\level\Level->useBreakOn()
#84 /src/pocketmine/level/Level__32bit(1019): pocketmine\block\Carpet->onUpdate()
#85 /src/pocketmine/level/Level__32bit(1434): pocketmine\level\Level->updateAround()
#86 /src/pocketmine/block/Block(571): pocketmine\level\Level->setBlock()
#87 /src/pocketmine/level/Level__32bit(1561): pocketmine\block\Block->onBreak()
#88 /src/pocketmine/Player__32bit(2226): pocketmine\level\Level->useBreakOn()
#89 /src/pocketmine/network/RakLibInterface(140): pocketmine\Player->handleDataPacket()
#90 /src/raklib/server/ServerHandler__32bit(90): pocketmine\network\RakLibInterface->handleEncapsulated()
#91 /src/pocketmine/network/RakLibInterface(81): raklib\server\ServerHandler->handlePacket()
#92 /src/pocketmine/network/Network(146): pocketmine\network\RakLibInterface->process()
#93 /src/pocketmine/Server__32bit(2491): pocketmine\network\Network->processInterfaces()
#94 /src/pocketmine/Server__32bit(2306): pocketmine\Server->tick()
#95 /src/pocketmine/Server__32bit(2184): pocketmine\Server->tickProcessor()
#96 /src/pocketmine/Server__32bit(1784): pocketmine\Server->start()
#97 /src/pocketmine/PocketMine(464): pocketmine\Server->__construct()
#98 (1): ()
#99 (0): {main}()

PocketMine-MP version: 1.5dev #1254 [Protocol 27; API 1.12.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT BASEMENT 6.2 build 9200 (Windows 8 Home Premium Edition) i586
PHP Version: 5.6.4
Zend version: 2.6.0
OS : WINNT, win

Loaded plugins:
BanItem 2.1 by LDX for API(s) 1.0.0
BlockMan 1.0.0 by SuperMarcus for API(s) 1.10.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
EasyMOTD 1.0a by LDX for API(s) 1.12.0
EssentialsPE 1.1.1 by LegendsOfMCPE Team for API(s) 1.12.0
FastTransfer 1.0.2 by shoghicp for API(s) 1.12.0
FireBlade 1.0.2 by aliuly for API(s) 1.10.0
ItemSneaking 1.3.0 by GmWM for API(s) 1.12.0
JoinCommands 1.4.1 by PixelGuy75 for API(s) 1.0.0
mcg76_SimplePortal 2.0.3 by minecraftgenius76 for API(s) 1.12.0
MCG76_WorldEdit 0.5.2 by minecraftgenius76 for API(s) 1.8.0
MoreCommands 1.1.3 by for API(s) 1.10.0, 1.11.0, 1.12.0
PeacefulSpawn 2.4 by LDX for API(s) 1.3.1, 1.4.0
PopupDisplayer 2.0.1 by Heromine, Flavius12 for API(s) 1.12.0
PurePerms 1.0.8 by 64FF00 for API(s) 1.9.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
TapToDo 2.1.2 by Falk for API(s) 1.0.0
TimeCommander 2 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0
TimeZones 2.0.1 by HotFireyDeath/Chopstick Software for API(s) 1.0.0
UniqueIdUtils 1.0.0 by 64FF00 for API(s) 1.12.0
VoteReward 2.1 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0
WorldEditArt 1.0.0_beta_dev_#048 by PEMapModder for API(s) 1.0.0
BouncyBlocks 1 by Darunia18 for API(s) 1.9.0
ChatCensor 1.4 by EvolSoft for API(s) 1.9.0
iControlU 1.3 by Falkirks for API(s) 1.6.0
iProtector 3.1a by LDX for API(s) 1.9.0
ManyWorlds 2.0.0 by aliuly for API(s) 1.10.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNXAtz20aS/iuzdKoipfgAwDdT8q0syYm3JItnyedUFluqITAksQIwCGYgipvKf7/umcGLkizZ
Aq8ulbKAefT06+vuwQD8syWDiLVm9qA/dQbT/tBqt1ia8rQ1+7Mltwl0tc5uzj59uvzUarciJgRd
YdsFvQ+iLCLLLPZkwGMSMyGDeEVCdsdCwpfkR9uyfiQpo96a+W1CFzzFAX8DMssgRBo9kXq9hHu3
TEZBzHowM5a9M/wXBoXQ1JoNB3+1W0mYrYK4NVvSULB2y+M+Q/YGQyDiymUQ05Ak2SIMvJKfFZOK
0kcasYPDP4HgYKSGuzJlMktj8oNcB6LzluWjyNHREXHdOAtD8l9wARRuvJAKcaBGHpLZgyk/I9mx
IvsXXk7gEv9OVVPvp5/gZmipG/IT+btZeMF5iB226cBrpxgk1ynfCFj/HfUvmFxz/4SG4dm9xxIU
DAf3zeAe3gzUza74gTihscfCkPla+uHQSB8sD/6mJSJBLCSOAmuZ0XQRskM9PteWKxVHYODNk0wd
uC2lbFiWxFxWqbmtQ9TScGzIoZ6GRk/DqWkETZG/39GUaCqaOyXeyHrUaBXxjNlkmilzjOzCHCNH
LzPqV8wxGhSaTmhKI2UN8sMdDTPWAl+TKfXAu/7ZemORXQe9YukdS29u+s4ikAfW4YyUna6reztv
vZSK9WkWJQeHsN4b+wEZ7c69ufpzQWNAVHowGvd36OlhrvuJrQIhWcr8c/wbqzVQ+6grvYbzYI15
SLclq1PbeoJ4jYkHdPvPqMCeTMc7hPXCnbc+lXROsV2TGjwgpSJF7xz/zelNBpNHlTqbLVJOfY8K
WaU5fAlNe2BNd4iqUa6rhnXeChb770LoFprq6AHVBfb21JiD4dh+hprUAxWt8Ys4HI52aaoVAW34
p/OWx+8gjhqSkyfYO6FpAoqZfF3YTDBF6zLW1KYvYtCyp48zqBdFDj8nYHFmXN56mWH6g6/zqkge
pzyLfUPYbtA2ttO8cex+o9axB3sxz3Bf5mkSOvYesGM3Cx57L+hx9oUep0n0OHtAj9Msepy9oMfZ
F3qcJtHj7AE9TrPocfaCnv6+0NNvEj39PaCn3yx6+ntBT39f6Ok3iZ7+HtDTbxY9/b2gZ7Av9Aya
RM9gD+gZNIuewV7QM9gXegZNomewB/QMmkXPYC/oGe4LPcMm0TPcA3qGzaJnuBf0DPeFnmGT6Bnu
AT3DZtEz3At6RvtCz6hJ9Iz2gJ5Rs+gZ7QU9o32hZ9QkekZ7QM+oWfSM9oKe8b7QM24SPeM9oGfc
LHrGe0HPeF/oGTf6uHoP6Bk3i57xXtAz2Rd6Jk2iZ7IH9EyaRc9kL+iZ7As9kybRM9nHac/kmaM9
x3FG32ahhwCKmdzw9Lb3id6eB4sPsWTpknoMj86eON1b09gP2enOGd/UoCilt2Gw6Al1dmeODH9V
M8oTyV3KhgfX3WEiX+ss9mgishAMaGw3tV8syAQ1rrlyXc1WfrRo+MqXqYnjPLnAR/0XNDR6sRxJ
yj0mzCHj9LmjVWcwtZ8ibVYvSBaL5MQHzxHvW6MnTq9lkLvzdPgcFXsy+AqVuWaOp4bc6LnD5PGT
5ISkaW6UhyCbq8sLuDwYjJ4icXPj8VjINPNyQhNygBo2d1OiDvT/jGgQ/wVt/2q3VnjWTkN81QRI
CHz5Ytayu0Of3cGURRaEfmtmO8NBuwWGkNzjMNYZt1s0CdRI2+laMHIVSLi1XvgfTNCeinO6Y0Uh
iym+pNP6EsQ+vhzy8Zq8O746uziDi1HXIYoXMnUsixzkYybkVx4xMk9ZFGQROfMDfFPjkATDyQhI
JusECA67o+4A7v7DYpCl5cCtpTtvuMAFP3z8eA0N6mYTxK3ibRyBanlH4w+SRXhpOMxb2hWVOV0b
7mkm1zwV+GrF+elvqF+lpn+CnixYFO5ZjC+MAB/4Lke75bMEuMIJ0Cf4Up5WG9BOQBtI4UspalHX
vcDGdivkFKWZX15df7n8dH4KTRu2EIEEDvH1HhBCxdoLGldZz5vaNXNbSiMV7q+yhKUXNPUyUZPC
foUYAmlGiqZJBxGNTUbQLL1AppOQ0fScrlYVocq2ulT2rlTnDNzdv1xenMzPmjJOsTgkI2Cfpc/I
0VpLmYhZrweIWWeLrsejXpWvXikNissjUJJ/nWLITqsy1zt2zbnjjFcel5LoNLBtzKB1HqCu2eXJ
6OHq+vjT9ef5I9Y8ZXfXnIeiIljRtGPLBy5aRkRyzWhUk6oPCvhOofL1XbfCydOCPGbOkrNeQQOE
PaNie3F5fVoRtmjasR/9eixRMfc1wSRf90XR5FGPPf2to7y1kAAFFILFMqChAHhVhKw27yLUfgyh
QkPhoV1fI3iVjaawWhMNNPCeCgnuH4tlDay15l2oOnUNiDVfrQMvaUzunKDrVtmo332zi+dEezUq
qIEgZe9Cql9ezcUv2p6RnYZBFjYXnzQ5113C+gtcH4SusPKCbIMZ9yqGjUUQVxNOrbkuU383TP0S
fblozJZIzHWry39LPfAPHsQmRlcjbq25Ls1gF5/z4J6Fv2Tb8bCp/FlSdN0qJ98iWOStxqObqyBK
YHPDU6nrWSPeI531ws3q9utCYlHtpXQpAelBJsajxuyneHHdTAawd62yVL/DF1Y/vFD2i5NfQLwv
PA19LH8rgu/2VKW2usNd8H1d6smrhc7fxt0gQwwYct2Ct28SmKfsES+uNe9mmbqBH8SXNl7Y+cVr
8BlSL2CplzKWiIsT142AK6/06DqPLxB2zmDHu8zCq4RuqnV8vb0irtMdfLV06CtEI7JfV0HUGPgW
rM55kiWngUjUU5aqSPWOXYzuBKJfWcrRY9vkfUjvwF9tpzGU1jnZFe7panaepWwOW5yqW5Ztu7lv
UhdoNHj/3rJqMky/X4QbTQ7slK9fufz2ghZn6h1xr6QCEuugdQxSVESuNNZlHj/IJjslfLv56qdk
Jg+xhrHvLukrVEAD1zS55qe8In7esvN0YDfcvqfhbVM5VNJEcp+7brn2C5B4HUR5NKoBsd5ejS3P
PuBoF7tukNf87Zu/r404Nba+JeLgxN95zMSOjLrtuTjDJdaM21NG5bp3suaJwOd+5ApY3dCUNWXC
giEtaM7bC8T7HAd/ZOyD/xmKiqqI9fZnnvc8En1eg7oi/NSY2Ll9VRiqUwI1/A+X7BMDk/gVHVQa
aznS/m5Pfo0Hl9x8i/sWRdJxWq3uas0PrHuzYJLe+Ozu5o012Mk087MLmlxwH9HdkPcmLKJJpEhW
CjyaVms8zee3brcrzPauIhqGnd9POrkTSKizehHFD8d6tXXw4SfPYm+rv3mqPgCtNlfUVveIU5pm
cUDtSVP5uCDoulUO6nffoZ6Cbq9GCJ8crqk8YbHgtaeGZePORq/uImd3PMQI15T45bovqKYKOTeb
TZcBJ0i1K29RquCExzLl4eeKUGVb1Z7d/oN0G6S39afZo++XKPD0opnrVtd/AZ6DeQpxwJM1w1Qa
q4aBav2ZR4HTV8akcuHXPwusCIH7NBpvFShru7SycTfxWv8nz4KgfNiqAPUNDxjwPAg/o2UQZ/Jl
1IlbN0l5wlIZYG3RejMv7gi4xDJYEfwI3E3d+M0Fj8lxtiK2RezJzJrO+gNyfHJNHMse4oCIS//o
PPNoGvAfBdEHetihF+okPJVH9tTuD7BxswbmOmEg5BFfLrGFxjHin3X0nqVDvXXA7ljEYinyMQK3
ap1E2wj0fmSplem9mSSOBqoFgizfdJZhsFrL+lwaBxCCgWBctkV8kTesQEWQBJgmvOQp8FO0GUJr
yH4ebIPz++QuMbP9YLkMvCyUWz1fn0yCM3UEk/hVvTjCZnXw30F3OlJ2LNsEY35lCH7Yf3R69v74
8/k1tmqv6UDVkG7NkqYpBSzn/OB1N6FCAHH/6Cf1H6gkk7wj6B0zE/H4sDh/7W6jEM1P0J+Ipyyf
Aef4iTo6AAFNkHID0bmYg0OQ6zUTjOSiESgliVwzgnUfXFBJPLSpJAtGgtgLM8iocEEeOB7SusJD
UL5EArs0BV3CHplDTyqQJFngexJky7PU0CLBkoCFgmWgVgDjpOAfgBUg/JFtCnI9ny0pmEeQDY9/
lIQmCaMpQdVEICx+Vb0F9on6rl3JvVmzmGTJKqU+EOi6MbqzJjZzY/Lmeg35uxNCE3AR0niV0RUj
+MsHSmXG9UUA95DWAMH/UUrFqSdr5hkp6hOBgTxEsbi7CW6DBEoR2uXpqod3Pfy+/IYvbz5cXd6M
+tOOc4PzQI0FoRlxIcSs3BYu9GXNUHdEcoLfUBOQkgiZKv1KfO6tXtbQ3UqbilPgA66YVCaFKizw
GNHvXmBLBIQ1Osol1c8+QLtYZ9LniCv9MxTIjI4GxAu5YL5m6xgxSjAC4O9RmNNqchdQ8t/o3zBE
+XnH9MwIhkqceLWGeRS9VHDgxqyiTUUNIZIJcEIIq+AISrrj+QcYib+IgHoqOzrA1gKYKsmfKUTl
dEBigmAn4K7gEcjqYkuMH8Fwg7+it1TDmy8BKJrH4FLU90nKhPY8ZFPtvyJGBWwHIvODDAuG+gCl
sz8yGqI5VsEdjFU/eUAOzJIQbg+BuF4PcM8wrHbAmqsVS2fQiyt/zKIFaBvgdCy2sXdNxS3BN1EA
QF3s/wxGUP6ZC4mj1imHAAwuAaNFm6jIREwEA5dtgxoi0JrAfKfUAhkG2yKo3jw1RNG+Ui4D8gC4
Un4P0VYyUAGIo1w9LlhDrWp2PiwRoTgEkdgmgfwRNCdTNctnGOuVF+7MJQcgAdiZOKgRJUPHSDkj
A4Qqxu10q4D6S8gXoFXMrUQ3g+tFgcSAFLEVXWwlcEOuNB+WWjkQ6pcxFMxBoE2guFKaJphfNJ1c
+UIpBQ9q4IKo3x5BKksIEPmK2vYgSaY8dsVBCI64QIXBOivFZEcxNiN9C7afKlSoqCwh1FD//7kE
WKrk/DuTnP85g5pAxX50fIFEPRX9DNXCuW1wBMC1jwZVIzrgfEy7tYqZUKYGMcABmFS/YvOEDJp3
qDFCFU4RWHqYq7Ib0gBXL2GjsY8rXCJeMZ2o4d2HgxGqpnoDZSfMw6wjlE6QV20NPbcQAMItS0Qp
Zt8ycorDRxkyUve11CuaLkDZHY+HoS570KMf1aqyHbJi5hAzB4ACVWOm8luVC8j9GXjNYTsH4I7b
GL/RQWy5zIEYlf7YJZc6uag7AcGfZ6FfMBIAXDcxKVlHJyGJ4hzyQqzWeK887kEMUm6iJxbyLFMe
5aEM55r+ThX9FXMC/8Zqu17wiOtU5mFF6a2z+FZoVZ8roGHgUY3IGZbcKAjRlWdbwSCFRC/0oA7m
WqwZSlpIKrewwch0ZPg85XraruUw2GJFoqdVKehVzLAGZFYBv+Ph70BpqY0b5AthR5Elv0rKjc0r
kEWJBF4R6oyzoBLqekz46g1OSDTgSiZ0KezpAtD06oi1YEXugeIhzzHGWfMexHy6lUi7TTp2xY8x
x6hlOzJnBSLKcKQDSpnT9E9iZZgbVZgzBtRzodHw1CW/wrYC1HtE8GiMnMw/t2EucLCA0LMJfLnW
0VFBuyDfUeRnZGwScJmahVJMZWiXHPsApTUNlz0opnW14DPwM7MQLKn9j8dVLBZZsEKrUtfcI+yw
2qBhW0Ma1zXvIXYJeA1Tno0p9fM8nucJuSyNsdbASer5H9bFcdIxt9XSBzZCbJGtZia3vyU25nRt
S4HFm+rOCzehItia5QWdaywxI3ZZjgnSE5LKDPylt/K0ZtUZZGXRfAtVK89ZXqsh3yCJ3piooca7
UFxlbw90KJWDmSkdPWVGIuhambIdBFJ7dmQXPA58VMUkWqNvfl9LVpYHZcqH3CiIKsu9+Xh5fTYj
Kt7C/14Ge5gY9jCKkDqvQdMp9szKBXtFxXlcs5YH5ToEEiOrciKVjIATdBqJjuNYJnlgJNM5Cb0I
94rYbhKRcaF6c5HmLQNJnQQXVLDKYgc24OSRVdrEgQ77sQ4mve6hwqxgVS6UO1wjZdzBmA0/wR+u
0+th0teWVHvFchOJcUBtNrBIwWhAww3dCk3b0Kn4US18Kzc6jngWV+O/MKVRzgSyj9SwMofQjJeq
BH1qKlXfNmjezRFtLekQe+o8Olt5V8z0dm3BNLUFW2IgUg8zMGChGQqq+hFHJfLpwHdF7yDn4o4v
wF0pw11OsjU7cJOKilJGBYqlekidR0UTxZZZqIZxAa7aQYgGns4kaqeT4rYXHAPI5qr6N8cNh8aG
wJ/zwx82RKfG/FLIv2MMVGhujAt6T+iuXswb9swv/aFuC+Wkn2AXn4nKNGMHarhTINVTjd/heCjE
MCbhs6SO/jSlZBB2tIzqRdTDrDIJasbL/VPOe/ch8yb+bWigtsKw7c2Ysa+Zr2Cv2jsCjDUjk++i
lvBEf5mButHXmJl2CLuxwmQHtIdM6ydmHeVHuLHCoh4MHqM3FK22CQ/4gAlDghpkTAoairMEah29
HdAOqYKHrjMMLaAyxllmQSQ6xNsNxYWKRtVGo0UAnq+HmGdbeis808EId+34+35Et+oUa5xEe6+p
4Yvghn7dweco9ZYindRak3USxEteusGao+3Vkt3KYzWogxR/MY+3ERb4CiF4/CoKRnHHYrpJ2a0Y
xh/nI3S1guxj9uDF0w0sEfE3EG8fl0bzg+TEY/ygvrQrKxPvzgaf0L0zbYA07pjkXBaAqpUnlecy
J/hoTj0rYiFPMFu1CZ7h4TMN4MRUYlCYLKFQZqBsyE8x5nkcZFJrhtYBPFaIEPOMvVJDZFBvCqkT
XB7wDDW0kO7O6YsdpeCRzCMqCQNIN9oqZ/cU862+wYIF6BsmZjk3qgucXUgOrv1PvOxAkoGNFDT8
CynqKJiXIdWHmkqIfLugt2v5g2K1D3vsGana1qosJlTFgGJHUEgEwKhJ8RXW1aqKAXVF8LkyQlel
pHK1GXl/fnw9c34et4fTe7vdv++3nZ/tn33IxDpqHeD5pIcR5mhikRX4t9B3g+GheobM7iWLUSHq
iOQE8lDlc5WFB9XIuvxBWBqCv9O0bNC/XGvu0OEqkyF5rIq+ZRBKfMOjZeVvuS1lUvSuAXb62Bg6
8Fjrruj6tzDHg/rrFqjktokseq/m54omvtjC/YVXEEm8tGTsE1uarRj0//ABNLlwaN+yhpPRZEK9
4cTyFs5k0vcGDvxjT5e+xSzLH/aH5Ad8IUhX4gU5/DFXXx3yF7JGW/FHqD7tMVdkiO9x2B3AAeng
EYtjDa0+XKrll/1xn9Gh7w+H/cl4ZA+sEZ1YjkMHiwntjwcDe7JwBhZTy0t+y2KI7UZ7+BVRkOTf
PamPivRHTPoVAbi+x7OA3CY8wi7L6tu2M4X++emlOaAf6O+r5ms0qDr+Qi3qV4t+uzgvVtv4/n1B
r0obrnHXUmEMWjZpICstXxi9hYChjdTFD6KgMC5JKG0FxWi8kayvv8jqaP6Egroopyz0s++iYUvV
2Uf+Jn9inmTk79KgUmCzceNzCaGiWCrSPmdo/I4J53KuEh4MGaN6cP33+LXAvdruKHoowl9//S/r
KV/A
===END CRASH DUMP===

**Comment by sekjun9878** [comment] 2015-08-11 06:44
This issue is a duplicate of #3053. Please download the latest PHP binary from jenkins.pocketmine.net as there was a bug in previous PHP builds. The latest one should fix the problem. If it does not, please reopen this issue with the PHP version and I'll have a look into it.

**Closed by sekjun9878** 2015-08-11 06:44 UTC

**Comment by Lucario2** [comment] 2015-08-12 21:33
Its not an issue with the php verision. I had this error for a while

**Comment by SkygridRex** [comment] 2015-08-15 20:12
@Lucario2 The Pocketmine Team it doesn't better to get answers they always close a important issues and never fix nothing (try to asking someone like a LDX or i dont know) i prefer make a estable version of pocketmine
