### ISSUE TITLE
PocketMine become no response

### ISSUE THREAD

**Issue by xxddff** [PocketMine/PocketMine-MP#2758] opened 2015-03-06 14:49 UTC
PocketMine usually become no response, and all the commands don't work, but it is still running.Why is this so?Please fix it.
I use PocketMine#954,do you have the same problem?
My plugins list:
EconomyJob v2.0.3, SimpleAuth v1.6.0, TapToDo v2.0.0, SpawnWithItems v2, RandomItem v4.2, TouchIt v1.1 Alpha, BackDeath v1.0.0, AlwaysSpawn v2.1.3, PocketGuard v2.1.1, TimeCapsule v1.1.1, essentialsTP v1.0.9, HealthStats v1.1.1, ItemCloud v1.1, AntiFly v1.2.2, Blood v1.0.0, EconomyAPI v2.0.5, SwaggyArmor v1, Fireworks v1.1.0, AreaProtect v1.0.1, PrizeWin v1.0.6, automaticDoor v1.0-alpha, TMDRL v1.0.0, Universe v1.0.0, WorldEditor v1.0.3, PvPWorlds v1, EconomySell v2.0.4, EconomyTax v2.0.2, EconomyAirport v2.0.3, EconomyLand v2.0.6, EconomyShop v2.0.4, EconomyProperty v2.0.3

**Comment by PEMapModder** [comment] 2015-03-06 15:05
You mean simply your console commands are ignored?

**Comment by xxddff** [comment] 2015-03-06 15:12
No,player also can't login to the server

**Comment by PEMapModder** [comment] 2015-03-06 15:27
An error occurred with one of the plugins. We don't support plugins here.

**Comment by xxddff** [comment] 2015-03-06 15:30
@PEMapModder Is it true? Is the problem that plugin?

**Comment by xxddff** [comment] 2015-03-06 15:31
@PEMapModder Is it true? Is the problem that plugin?

**Comment by iJoshuaHD** [comment] 2015-03-07 00:42
@PEMapModder i think he has the Console freezing bug too.

**Comment by PEMapModder** [comment] 2015-03-07 03:28
He said "can't login to the server", which means it's a plugin causing infinite loops. It is most likely caused by a plugin.

**Comment by xxddff** [comment] 2015-03-07 03:33
But my plug-in running normally
![1](https://cloud.githubusercontent.com/assets/11043135/6539879/b3f55d54-c4bd-11e4-838b-05cb99cded3f.jpg)

**Comment by xxddff** [comment] 2015-03-07 08:09
Like this
![1](https://cloud.githubusercontent.com/assets/11043135/6540641/40826b4c-c4e4-11e4-859d-601a8e6941b7.jpg)
but it is still running

**Comment by jython234** [comment] 2015-03-07 22:02
@xxddff, @PEMapModder is right, something is running a loop preventing the main thread from running I think.

**Comment by 3do2** [comment] 2015-03-08 21:57
Is it like this : #2532

**Comment by bgbrandongomez** [comment] 2015-03-09 02:00
I have had issues with random plugins doing that to me such as MineReset and EssentialsPE. Deleting the config of the problem plugins can help when the server is reloaded.

To figure out the problem plugin(s), using process of elimination can help find it in which I would stick 10 plugins in at a time and  reload the server to see if it still works or breaks. Since it could be more than one, keep trying until all groups have been added then chunk the groups to smaller bits. It's just what I sometimes have to do. Hope it helps you.

**Comment by xxddff** [comment] 2015-03-09 05:56
@bgbrandongomez You mean let me one investigation Plugin problem？

**Comment by xxddff** [comment] 2015-03-09 05:57
@3do2  Yes, I and your situation is the same.
Find a solution yet?

**Comment by bgbrandongomez** [comment] 2015-03-09 12:54
Yes, I mean if your cause is truly a plugin, it could be caused by the plugin's config. It doesn't happen instantly, but it can randomly break. When I viewed the problem plugin's config when I had the problem under Notepad++, it looked the same as a functional plugin, but one worked and one didn't. So it could be something with hexadecimal values such as an accidental enter key from the plugin or a missing tab or something weird and random like that. My solution is really only a quick fix, but it can be used by someone who has the time to investigate to actually solve the problem with this bug.

**Comment by sekjun9878** [comment] 2015-03-21 11:21
Sounds like a duplicate of #2532. Please reopen if there are significant differences. If not, please continue discussion on #2532.

**Closed by sekjun9878** 2015-03-21 11:21 UTC
