### ISSUE TITLE
Unlimited axe, pickaxe, shovel etc etc...

### ISSUE THREAD

**Issue by Jelly9912** [PocketMine/PocketMine-MP#3789] opened 2015-12-20 11:16 UTC
And somoetimes bugs with crafting

**Comment by HittmanA** [comment] 2015-12-22 21:49
I have this problem to! All the tools on my server take no damage whatsoever! Even wooden ones!!

**Comment by Jelly9912** [comment] 2015-12-23 01:24
Update: if i hit players or mobs then tool in hand get some damage. Tested only on diamond axe, can someone test it on other tools? 
Thanks

**Comment by HittmanA** [comment] 2015-12-23 14:28
I will test it later today.

**Comment by EpicnessTwo** [comment] 2015-12-27 21:06
Can confirm that all tools only take damage when using them to harm mobs. Block damage is not working at all

**Comment by 19kestier** [comment] 2016-01-17 12:29
Duplicate of #3555

**Comment by PEMapModder** [comment] 2016-03-07 10:39
Cannot be reproduced

**Closed by PEMapModder** 2016-03-07 10:39 UTC
