### ISSUE TITLE
Bow Issues

### ISSUE THREAD

**Issue by Samueljh1** [PocketMine/PocketMine-MP#4029] opened 2016-03-07 21:22 UTC
### Issue description

An error sometimes occurs when shooting a bow when it is not fully charged.
### Steps to reproduce the issue

Quickly shoot an arrow multiple times without fully charging the bow
### OS and versions

MacOS - PM 1.6dev
### Crashdump, backtrace or other files

```
[21:18:20] [Server thread/CRITICAL]: TypeError: "Argument 2 passed to pocketmine\nbt\NBT::matchTree() must be an instance of pocketmine\nbt\tag\CompoundTag, null given, called in phar:///Users/samuel/SkyWars/PocketMine-MP.phar/src/pocketmine/item/Item.php on line 1154" (EXCEPTION) in "/src/pocketmine/nbt/NBT" at line 152
[21:18:20] [Server thread/DEBUG]: #0 /src/pocketmine/inventory/SimpleTransactionGroup(111): pocketmine\item\Item->deepEquals(pocketmine\item\Arrow Item Arrow (262:0)x4)
[21:18:20] [Server thread/DEBUG]: #1 /src/pocketmine/inventory/SimpleTransactionGroup(133): pocketmine\inventory\SimpleTransactionGroup->matchItems(array Array(), array Array())
[21:18:20] [Server thread/DEBUG]: #2 /src/pocketmine/Player(2809): pocketmine\inventory\SimpleTransactionGroup->canExecute(boolean)
[21:18:20] [Server thread/DEBUG]: #3 /src/pocketmine/network/RakLibInterface(136): pocketmine\Player->handleDataPacket(pocketmine\network\protocol\ContainerSetSlotPacket object)
[21:18:20] [Server thread/DEBUG]: #4 /src/raklib/server/ServerHandler(92): pocketmine\network\RakLibInterface->handleEncapsulated(string 10.0.1.14:19132, raklib\protocol\EncapsulatedPacket `.p....................., integer 0)
[21:18:20] [Server thread/DEBUG]: #5 /src/pocketmine/network/RakLibInterface(77): raklib\server\ServerHandler->handlePacket(boolean)
[21:18:20] [Server thread/DEBUG]: #6 /src/pocketmine/network/Network(141): pocketmine\network\RakLibInterface->process(boolean)
[21:18:20] [Server thread/DEBUG]: #7 /src/pocketmine/Server(2397): pocketmine\network\Network->processInterfaces(boolean)
[21:18:20] [Server thread/DEBUG]: #8 /src/pocketmine/Server(2153): pocketmine\Server->tick(boolean)
[21:18:20] [Server thread/DEBUG]: #9 /src/pocketmine/Server(2033): pocketmine\Server->tickProcessor(boolean)
[21:18:20] [Server thread/DEBUG]: #10 /src/pocketmine/Server(1652): pocketmine\Server->start(boolean)
[21:18:20] [Server thread/DEBUG]: #11 /src/pocketmine/PocketMine(464): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///Users/samuel/SkyWars/PocketMine-MP.phar/, string /Users/samuel/SkyWars/, string /Users/samuel/SkyWars/plugins/)
[21:18:20] [Server thread/DEBUG]: #12 (1): require_once(string phar:///Users/samuel/SkyWars/PocketMine-MP.phar/src/pocketmine/PocketMine.php)
```

**Comment by jingz2007** [comment] 2016-04-05 21:18
I can reproduce on RasPi 2 PHP7 pocketmine for v0.14.0 @Samueljh1

**Comment by PEMapModder** [comment] 2016-04-06 11:23
@jingz2007 we don't need your confirmation that the issue exists. If the issue is not closed, this means it is pending for being reproduced and debugged. Your claim that it is reproduced does not help us debugging it.

**Comment by dktapps** [comment] 2017-12-31 11:22
This has long since been fixed on PMMP's PocketMine-MP.

**Closed by dktapps** 2017-12-31 11:22 UTC
