### ISSUE TITLE
Player Hit Issue

### ISSUE THREAD

**Issue by ClanEmo** [PocketMine/PocketMine-MP#3894] opened 2016-01-23 07:34 UTC
When I am trying to hit a player they can't take any damage but they sure take the falling damage, Like PvP is disabled but not

**Comment by PocketKiller** [comment] 2016-01-23 07:45
remove all plugins, then test

**Comment by MilkoIvanov** [comment] 2016-01-23 18:25
Maybe the difficulty is not 1?

**Comment by PEMapModder** [comment] 2016-03-07 10:28
Probably fixed by #3978. Cannot reproduce.

**Closed by PEMapModder** 2016-03-07 10:28 UTC
