### ISSUE TITLE
Server freeze, console can write, but not answers

### ISSUE THREAD

**Issue by wrewolf** [PocketMine/PocketMine-MP#2638] opened 2015-02-16 20:18 UTC
restart server only by 
kill -9 pid

log collectet by.
https://gist.github.com/shoghicp/2b93ac93664561c0e9e4#file-analysishangup-sh

http://pastebin.com/zvgX6ncx

**Comment by unerds** [comment] 2015-02-17 00:44
encountered this several times as well.

**Comment by Subtleoliver** [comment] 2015-02-17 16:06
Also seen it a lot of times

**Comment by icsmoke** [comment] 2015-02-18 03:47
yes, i had this problem too, but now this problem not happen to me xD, are you use Economys Plugins?

**Comment by iJoshuaHD** [comment] 2015-02-18 16:36
duplicate issue : https://github.com/PocketMine/PocketMine-MP/issues/2532

**Comment by 3do2** [comment] 2015-02-19 19:10
@shoghicp told me today it can be a php binary issue.
I've recomplied php for 5.6.5 (last php build) on debian.
My server is running, i'm waiting...
Shoghicp, told me to test 5.6.1 too because, it can come from a bug in the last php build... if someone can test...

**Comment by Alcatraz-Du** [comment] 2015-02-20 05:54
You should use 5.6.2binary.
It can solve the issue

**Comment by wrewolf** [comment] 2015-02-20 12:00
my version PHP 5.6.4 (cli) (built: Jan 12 2015 13:12:12)

**Comment by crazyravenspeep** [comment] 2015-02-20 12:02
Stop sending me this stuff I don't care!!!!!!!😑😤😤😡😡😡😡😡

**Comment by wrewolf** [comment] 2015-02-20 12:03
@crazyravenspeep unwatch this repo

**Comment by 3do2** [comment] 2015-02-20 13:26
@wrewolf  goto https://github.com/PocketMine/PocketMine-MP/issues/2532

**Comment by wrewolf** [comment] 2015-02-27 17:44
Freeze on on 5.6.6 too

**Comment by sekjun9878** [comment] 2015-03-21 11:25
Duplicate of #2532.

**Closed by sekjun9878** 2015-03-21 11:25 UTC
