### ISSUE TITLE
furnace bug

### ISSUE THREAD

**Issue by Creeperface01** [PocketMine/PocketMine-MP#3749] opened 2015-11-28 09:33 UTC
if i place furnace and go away and then go back and open furnace, so it crash the game

**Comment by blindahl** [comment] 2016-01-10 19:22
Same bug as issue #3814

**Comment by Creeperface01** [comment] 2016-01-10 19:48
Yes but my was first :D and this bug is due to furnace should be spawnable

**Comment by rick123159** [comment] 2016-02-29 14:09
This BUG is existence on the new version now. 
(
VERSION = "1.6dev"
API_VERSION = "2.0.0"
)

**Comment by thebigsmileXD** [comment] 2016-04-03 01:25
Hasnt this been fixed for ages?

**Comment by gillouz** [comment] 2016-04-03 09:06
Hi everyone 

I am running this version and this bug is still open (crash client IOS and Android)

This server is running PocketMine-MP 1.6dev-23 「[REDACTED]」 implementing API version 2.0.0 for Minecraft: PE v0.14.0.0 alpha (protocol version 45)

**Comment by amaax** [comment] 2016-04-03 16:01
Hello
I have same bug
PocketMine-MP version 1.6dev "[REDACTED]"

**Comment by PEMapModder** [comment] 2016-04-03 16:03
Not confirmed existent or nonexistent yet.

**Comment by amaax** [comment] 2016-04-03 16:08
How I got bug:
1. Put furnace in survival and make it work
2. Switch to creative
3. Reconnect server
4. Try to tap the furnace

**Comment by amaax** [comment] 2016-04-03 16:13
3.5 Switch to survival

**Comment by dktapps** [comment] 2017-12-31 11:24
This has long since been fixed on PMMP's PocketMine-MP.

**Closed by dktapps** 2017-12-31 11:24 UTC
