### ISSUE TITLE
Stop when is overload

### ISSUE THREAD

**Issue by Yupai** [PocketMine/PocketMine-MP#4055] opened 2016-03-10 04:47 UTC
### Issue description

My Server stops when is overloads. I understand that this happens because I have little RAM but it didn't happen with php5. Can you fix it? or is it normal? Thank you.

### Steps to reproduce the issue

1. My server stops when is overloads
2. It did not happen this with php5

### OS and versions

* PocketMine-MP: 1.6  (Minecraft PE 0.14.0) 
[CrashDump_Sat_Mar_5-14.09.23-PST_2016.docx](https://github.com/PocketMine/PocketMine-MP/files/166533/CrashDump_Sat_Mar_5-14.09.23-PST_2016.docx)

* PHP: PHP7
* OS: Linux

### Crashdump, backtrace or other files

```
PocketMine-MP Crash Dump Wed Mar 9 15:53:21 PST 2016

Error: Allowed memory size of 2097152000 bytes exhausted (tried to allocate 339968 bytes)
File: /home/minecraft/multicraft/jar/pocketmine/src/pocketmine/Server__64bit
Line: 1808
Type: E_ERROR

Code:
[1799] 			if($p->isConnected()){
[1800] 				$targets[] = $this->identifiers[\spl_object_hash($p)];
[1801] 			}
[1802] 		}
[1803] 
[1804] 		if(!$forceSync and $this->networkCompressionAsync){
[1805] 			$task = new CompressBatchedTask($str, $targets, $this->networkCompressionLevel);
[1806] 			$this->getScheduler()->scheduleAsyncTask($task);
[1807] 		}else{
[1808] 			$this->broadcastPacketsCallback(\zlib_encode($str, ZLIB_ENCODING_DEFLATE, $this->networkCompressionLevel), $targets);
[1809] 		}
[1810] 
[1811] 		Timings::$playerNetworkTimer->stopTiming();
[1812] 	}
[1813] 
[1814] 	public function broadcastPacketsCallback($data, array $identifiers){
[1815] 		$pk = new BatchPacket();
[1816] 		$pk->payload = $data;
[1817] 		$pk->encode();
[1818] 		$pk->isEncoded = \true;

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6dev #0 [Protocol 45; API 2.0.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux mcpe6.netherbox.com 2.6.32-042stab108.8 #1 SMP Wed Jul 22 17:23:23 MSK 2015 x86_64
PHP Version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

Loaded plugins:
RealTime 2.1.1 by Guillaume351 for API(s) 1.0.0, 2.0.0
FirebowTP 1.0.0 by Minifixio for API(s) 1.8.0, 2.0.0
PerWorldChat 1.3 by EvolSoft for API(s) 1.10.0, 2.0.0
TapToDo 2.2.1 by Falk for API(s) 1.0.0, 2.0.0
AdvancedKits 1.2 by luca28pet for API(s) 1.10.0, 2.0.0
PopupAlerts 1.3 by EvolSoft for API(s) 1.12.0, 2.0.0
Yupai_BUHC 1_by_abel by TheAbel for API(s) 1.1.0, 2.0.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 2.0.0
AlwaysSpawn 2.2.2 by Philip Shilling for API(s) 1.12.0, 2.0.0
FlameBows 1.0.0 by MCPEPIG for API(s) 1.0.0, 2.0.0
1vs1 0.0.3 by  for API(s) 1.0.0, 1.1.0, 2.0.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0, 2.0.0
WorldProtect 2.1.2 by aliuly for API(s) 1.10.0, 1.12.0, 2.0.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0, 2.0.0
FoodEffect 1.0.0 by MUedsa for API(s) 1.12.0, 2.0.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1, 2.0.0
MultiTP 1.0.0 by Minifixio for API(s) 1.8.0, 2.0.0
VIPSlots 0.0.4 by iJoshuaHD for API(s) 1.12.0, 2.0.0
PurePerms 1.2.2 by 64FF00 for API(s) 1.12.0, 2.0.0
EconomyShop 2.0.7 by onebone for API(s) 1.12.0, 2.0.0
EconomyPotionDispenser 0.0.2 by Khinenw for API(s) 1.12.0, 2.0.0
Lightning_Strike 2 by MichaelM04 for API(s) 1.0.0, 2.0.0
WalkingParticles 0.3 by hoyinm for API(s) 1.12.0, 2.0.0
InventoryClear 1.3 by CrazedMiner for API(s) 1.11.0, 2.0.0
iProtector 3.1a by LDX for API(s) 1.9.0, 2.0.0
EasyMessages 1.1.0 by Gamecrafter for API(s) 1.12.0, 2.0.0
PerWorldAlerts 1.1 by EvolSoft for API(s) 1.9.0, 2.0.0
WorldMonitor 2.0.0.000.0 by Steven for API(s) 1.2.0, 2.0.0
SimpleAuthHelper 2.0.4 by aliuly for API(s) 1.12.0, 2.0.0
SignWarp 1.5.1 by aliuly for API(s) 1.10.0, 1.12.0, 2.0.0
PureChat 1.4.0 by 64FF00 for API(s) 1.13.0, 2.0.0
SimpleWarp 2.1.0 by Falkirks for API(s) 1.12.0, 2.0.0
KillRate 1.2.3 by aliuly for API(s) 1.10.0, 2.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrVPIty2za2v4Ire2btHVHWw5ZtddwZ13bSbO1EazlN75YdD0RCImKSYAnQstLpv+85AEiClL1x
Em/v3L4iHAIH5/0Awf7RUTxhnclg/+DwYHw47g+6HZbnIu9M/uiodQaPOhe3F9fX76473U7CpKRL
hJ3GsVixkCQsEfmaSP6JEbEgw/7x4eBg2O/3yXytmCTsIaKFVDBzR+Uc/lCCUFgbUMXIaHR8PD4y
M3cB/YLHiHsvEgnbS3jKgpwu1F5SxIqbnx9pvpeJ4I4pfLwn88Adzlh+z/Lb2/H+nCvAFwMQWDvq
H/3Z7WRxseRpZ7KgsWTdTiBChjwODo+PYU9f4d98sbOded9zeSZS2B3I3tnd/QMwAY5+NctX24rm
S6bkr7+RE7KtIi5hUchSQMBZLn/1fZnFt2L+EXDcRlRGgHb3t+8MokGF6E8DGFqAHY5gaH7t2wdA
1v9sL0QesNk6DQhNw3LTlKmVyO/ORJLloBsu0lMJU0qaD6qtgGJ5B8SmbEXK2T9QFUQsvIEnO9tS
5V1S8tV9Gv8lu2fxrmVl7ODX82HxDHEWMct3dr3vpR1oqsxGSEi5/rDknIFOLM1HbZzzXNAwoFJN
KWpanoH9zOHnju9/ivn8lqWoS8vBvy7f/HB78fbs3fmbt69vzy9eXZ7eXHyWnZrzkrLjhk4G/VIn
g1J7NxxMbiknk+0spmuWvzWoAcxy4FuJzMzYsRgHRssWX6XjgdFxVsxjHpBFkQYKqCJP8rwdUkW7
hOY5XZNtx+asygelyrezUt1azQZPRcy4nuV9n9F1DNuhKSN2O+XQnWJlXC4/cp9xeaGfIgLfV3nB
vuuAv6mcBuBhv3a2+mRnd0JqP/V946je9+DUMjovkmxnLkTMaLrb+a3bWbKU5TRG74RZqCXYbtAb
h+wetp8XPA47kz54dC6UCARM3D/odmjGYdqw1+/1YdYSAsCk03/mX7Agp3dgTLimd6QxFCnFwNi5
5GnxQJIgY+Me2E/E8rl46AUiIcPeuDcaev39oVR0Pugf9Y7I1oDMrqbkA0jjH0VMhkMyOJwMR/AP
uZr9BPFxcEAejsYQomCLLMpgg0MgeQSjTywFvjojywE8vBWyJAAAehDrQRXOJArpmtH4RkfxPzqW
6ArUdUQ47A16A4DQQkUil6ib1yDMmBYJGx0MUPRaiL+CsA0NRpoAZymdxwzIQ/V2OyHLgFjEAM+k
WKhzF5BQjLMVDb5/BYCzmEqJMRksDR5O381uPry7vjwH0IrNJVdAdlrEMbD2iudsLlY3U4ehGtZt
GIWh0+HoiqfgEA9cNNg5+nZ2/rfIKPf9hSFEZb6PNP1gaXoGW1OWfxB5HJ5FVDmcNcBN5kZN1i7u
RTwD6hqcDV5AUy4JRls1R7Ob0+ub91OXn06kVCYne3ur1arHgCjE21N3aJY3NLsR58Lhr4Q0LXHY
tsRXNL57aQtUNFMiFL5f0/AMPZ2G9zQNWPgTV9LhowF2mBn0hg1G4iKgw6OMvbyaXAraanqUoUpR
EA2jYo5Ba68ib6/BENqnyIrsFBJ3g20X+hXWOXwB66wpeK5xPm6b2oNvf3j/45nDnwNssHc7X9/S
OYubTN5E7BSBDR6/ncXXQIu8BJ58/wdMb0DNsxRsLfYiEKlI1qfTNw5jDrDpev3ecZMpkUJEg0p5
0/tK5sDGqz8H+s+RHY/seN+O9/X4m4RhyfF9ZjgAmny/wc1znDhe0bWcZXSVuj7sQNvxaNgUyjTi
Mc/IDP6AnLt8cavONH5p0fs+1aRJJM330RRY/h/tvMyVMXAGSch12Rr2uVx5Nr2Yvnn90mHXooUE
WRLyJcY8uJcDhxk9dPno23Kp5uNpu/02NspKwvfBHO+ltsl3KftZwn+ex8uMJxk0P0Cpw5EDbOrn
sJ0Tp7pkBjoYuWE0gYcyEsuIB9mLm2NNFFTnLoHPKAOc7FJTvOdgAUno+mIKBTt0xI4sGuB2rdry
SBrzIl4/llVfRgQGv++vkKbM0PQl1ZAjBhqzj9Cl5wJQOgcUni3a91TO2F4C7R3L9xoiAEmdFdA8
Jht5uAFu2s34L0rELgm+3yLoqzLyKyHCi8WiaRMO8HPx6z0LJX1xPmsCnt+6uEwGVIFi170gRR7P
2f0NNLeuLitQk7/BBoPtAOByOvr2TFvS4fsORV/t8BUOYPoKj+waDVwJ+b9q35xors8TsYGraXpG
LP/5zXQWi4ZPVqB2ftpvMsX/IWRU0B/PX9xUK8y+7xDzZSrkHzWOKNyrUGA3UOQM+sKk0QtUsKYW
N4qn8f6rV/3+i3N7a/D6fkWI8/PLTRdX2oBcY6nL6Vkkss16WkPbBfXh5wvqZ/PvFu5fUCVDZZBV
ZbIl8vmtw1TgseM5l7CRZPkm2+0JbYtvGcBPEUSEdPVflYDdA0ygSRtEM4fMZ8jgki8jlUIVfjtT
Ob9zz9E2Hjl8D1uBK4goi6/6+y9dTlc0GBKgO2gCnsfkBxrfwZIpzRUPYua69cYjh0motRtsRmLN
0+TFPbtNgu8/QtQzuHyT3rNUiXx9FjPqmnHrQeP8psnhWU4/sRAzWt5k8wVaCt9v0vElfRG3NaJw
2XKArkdCbUCbDnl5/kuDm+MXsMvzX3y/JuCrT6QAj4ct457DDEYmKtdX5n2ja6wNcKt+ahcTeKyi
3xu2VfkCFsuADvs6FKzVperzZxSPScGh1SmqvOkjHUNDBM7B8ubZXfNBS1rP6BqOX+5s+csO8J44
XdaYrkTKm17QALdzM/zd3ygzZ4qBHzZ4fYko5tDxJa5dt8o/sjhrpN+NR2329j/fJD877zot+zP6
5EgT9NVu/yU98oYUtNCW6QeaZw1hWVDT0g/atv7fOUnovAJib3KayoXWU6Ox3xSfBGJXQOxfJEAr
GVvZt99BlaCm4PbbbvNYXT96rnXVNfZjotPvvSWIC5D9wu65KOT0wivhnSeaAPPGyiH/S4XYbgI0
msolN+yrArbPqvqbb7N4fidfKO20TQu6tJUzvJAS7wHQGETmSGphiUBbQ8KNtTWYeEZw+onH8TVV
blVcgdpt4Oi5fvY1MrBZEZqeNWC4olLye2ZbhU63+b7jtYjDmQofcbs7oD0H2v8St6sE9Se+sac5
iA/AJXv6EkQvywVENMWxyulsTasRORPpgi8JXorycz/dwjsFVzQnx2RwMBn1J/0Rmc5u8ErBGJ8n
QoUnftHv08PY/DH2i+FwfEDMaK7fdNnBwrM/jqcW8HM5Ju7ifcS8ikAYXsylOhGLBUJomooiDZBp
vPvi0SDikFATsEJZztGvMjx7jgomcmLIxMtfK28RYw/TnEpTnoAJn4i0hiViXgKWFO+aheykjyN9
G8qrYBZRRPMwEHk1zu4zuzrkiwUPilitTwYam75jAnnak0wpvMlzguAYrwMBiIXOEK/BneBFIgQZ
g/V+L1i+trgtKAcDLDfG370MTHQl8vDk7/ov4L1QwpP0vqIvZ6FUYNBeQGMgjmo5lQRLjTUWS7SA
SlTm5gzPTgb9/d5o3Ds66A37R86jTOTqZDjuH2tgQh+skuTJsF/zhJ58ok+6EYbXTSpL7q2TGE2R
oIOQQFthkWvatDESkD1xStSrqTZPchMxyUgpTkJzRlTECLAn4QdVJECzUWTOCE+DuMAbQ7DBhhsY
bDOR6BuFahOrpAvWJQKv4khESuY5o3dkLYrcYiN8QcAu8GYU7gEmkYMRgvtr1G/ZqkK4F7IFBbOQ
ZCXSvylCswz6MoKaSoBl0Eu8BhYI3h8z3K8ilpIiW+Y0BAQ9RGmkbxBOcEC2biIIA17M8CSYxDRd
FlCtE7wmpcVndSU5jPEyZMw/aQGbxWcRCyw/zaVASBmRWNpb8TuesZDTnsiXezjauwQnvRWL2zez
d7fj0bE3vMV1WqQVqgnxIewu/Y7Z7EOkLzXhxUzIIiHeziRS5VraCnMMmKW5t2llq+kFWuAXU1rF
IeTrgJEIwmKslZ5o1MZH6231zUv9REaFCgX6t2ljkCQbpa4ZT3nAAZUgeE2MhyLv2ZhEfy5YfM8I
KiAFBWO8EQQMHlDfw7SSJX05lWDAAi6IDczknlPyT3RbPUk7cBm0JwTTj1k8i2AtRbuXArixFBq1
U4uMFBKMGpIVmJWWDmQdmAmJLzSyrh9593hhTDJ3iwsdMEpceJ0TgxYBFwALQ5Lna2LtUi+wAaZ6
7opy6wPkGDAMMFMahiRn0lgzkgv2ewdkUQmFDcqKgA3PGcoGRMZ+L2iMal1CGk3JPY0LRnbstpBV
djV6sycEN4ZxxQO7WC5ZPiEmlpCtt0UyB5sAR62ueBK8Bwmu2TMz3kuQD9p8yS7Oi3JI1gUYGMyX
XaIDEbExGdygCwKprmhqAUFKRlhSgHHoKRb7TJsg8AWOm4sHyCCKgSiALe0+aUUeSrgk6c0C/V9f
RQY/7xKu/gYyVLleFzJMWNquW6vJDnABmidDIxvNiWe5nWhcZTQw16JtLHgdizmIGsuZ8r50zBOu
MPolbEn1/ecemRmS+poIE/3LWAL8rbgmUYufYAo1mEqNSC0lvJwGPwg2txrZAqJQuacxCWCr0Aa9
FMCRQIdG+emdlppQTxM3If2SGbKlM4GCkEbD/wdsYMX3GSawUPhGJvCKr6bDhsWKLotPEnA7LAFY
WFOF+5ak4S35mjrojLjQCRG9VuLGgU4DlsrKMwewIQSn0NignuNhQVv6pE0hAhqCFDwaZIkR5SlR
GxFDhRfr7IKxwUwz2A0W8NTa88swZvZ5h4EHs61e1NtcgIKwRT6INWMBJmWpBYVUG7mbtRUrIFuW
yZrlUd/yLHefIMtKYFRLYEnzOdiHF4g4NgWo8cZHJa0NDkmyq4hdBf6e0LTQRYBLDZRJBX6z0C3j
yIahWEsxcVm/S9b4k9oGe+Sdybt6BNYSiSIOK1I4xJ1VSmryjW2TTFMPrI5d8yFbr7TPbMRWbUcG
R8XcIhdJGaTNajvDcyNaS9PAkFXoppk8Yl2t1ViGBlGR3slSC5faSzC0ajDSqS+hA3/EFKxd7dY5
lEjSTPKwPsGaq8ZmkJVGYB3reOxQfS7M4rZqMbFgXWeWNvGY3ezEF5WDTnRQ7YOtl5IoC327KT5y
aoXPosR/7WcNTukJxhSbrDvH2/+6DDJfEnTR8G2U085rCmz71IS2Oavyrw1eW25ALJ9h8MjXCrF3
iTdwXMDkWb21p0pyIEAdjMvoVGd33Y9gWg1NCLVKNqsBaCnrkR+hZQSxn0DhB6Z+Nn3fhbVAxRzi
2IqHKjIZwUaIagNPbzAhh1U5UpcqUovImdwjpyH4YkTjxR40LqaCChnYo90MtjV2KlLXmZ16wMHW
qNMuHtB1sQyjcdcEBtz8A4dKdwXsgVkx7QZYYbyfptOyPqn7ECzBcNEKsohGWmRp5llAsy7ULSSb
F8tJVfJ8TwZY6tjshVWunlBWuFJHxIiVla/pGYzsBm7dKsmeVFQVYEp7y6AUN8TJULYIKLvpVmfE
yuIWeQHuTHeoJ1sDRBFoYwhAuMraoF3kmUUTksDDZdUzAYP6CAnJv8dXDSbM0cYeEJGxA1UOCSBk
tUmR9m2r1q23724uJkTHc/gnKKCZTKGZ1Kj0YRoq1RJpd6+IdAzgtKHLALoliEaWa21nOvUBPWhX
Cm1r2LcpCoOiyYDG0PAcAZ/YtFdFi+aDutCofNgk3jmVzNlyZwBO9cheXTKEB4PHHjAV9Hatk0vm
0mJN5QaxYytpDx8Ig8Bm9sSSw2hXt/B1b4/BQ3duWMmZEGJuxRr8FlPLxhqZwZrYaSKK1E0u0taR
JTHICuI0LQ5EfBxMyP5/Wk5zgIaGD4OnndnI4Hj4BAZtfSkzffScGYxztsBIpk+6MOKhahzM5gTM
CZ9l9JxR6IEp1p0cDw4Yto/Z2h6W2GxXlVU6yCz0cWQZWqtAuChiPVFIMGcPnZoHJkXpBjLHswkw
GUBcCu6jwA7OeJCkCVpRYiMuJq5KEo+oCEVcq+iKPhDalhJ0cIHOObW1tDVkTfmahryQzlKrHWop
1W5dLrfWiSugbjJxDY8fvSILwWZdckmAr+WNveH5QTPXGkbqNrXmpbfJjI2mK8r1KcTvBSuY1b7F
YEOGfuLhF7QTcvSVGDORFXGF0Y4w+W0gx3+1P3sgVcOAOXj1tL1JlLERcgJ5QOEhlYUPqhCDR5gT
Uhagperx+70ig/KrrkuNCeswVJY7FivgOzSr7fa4wYEBrChuW4EtlCZzDl5TTtNnyRjuzMnEpAxx
eJiCXxUSAzcZ3hpWafu2H3ECJ3qGh0dlbViVvFrwLMp4uhCu6UQC7UVv3nNOU6E4q+hNRbpOsG3R
viZBD9IhHDsyO4HUEzQD+F0mocslZDx7QFIdRGFNi99a3j3NnaEMUcqnKENJGnewRrGJBazJzJiU
aspTzxYLbsWq4SJrHKqd4SmtPihkscgwX3ZhDDzhWaiqS0aonBZQ8zNQBuTHFGsPnFal+AJ1CF7u
ICL2FZRT2xRQJktlUmwZWC0+o0EzodxDbogKrx48IaiYQ8IrtXbxQDH/l0MsqmAvS9CkpMw+BKfB
M4MJ+RV/epDquvoQ4bcSt4m8dZnknntrxsp+yLSq5RsM3YM+dpCuG3ydUaWuZlAU+u4rkGwLjwYb
dmdNhv1N8FUIhgSbGutdJwTfiEyG3x12D44fBt3Rw6g7/G7wXQgVgomOO/gmLMAYdnLUJ0vwC2lG
+we79qUDe1AslfoF7+SPzhlkQ+d72FC/dKyGWdB4Kn+PuWIjff3w0DOfBn8yX/CWU+YBlFuRA8Bz
6zTEe2E1yP4/DqpxkcfOcMFjvDzkAJT7ye4ydAeJ+wi/+jdXnGHwUTbeqCdzc8DuTIdidp0plz9F
kVR3g9n0siEPKEJdDGsQif6C2P4iB/BkMETZEE9/edzf7x/Cz+03oNLFwTGbH44PF2xwSMfjw+OD
o+P5QdA/HIfHC3p0FI7CfcjCfbINuKeRFtrQXvTMhOQPLin2DMPcPNPfI1yzhe2yXZ6iRLgyktrF
ZJsJ7gCUuGMpZC9XBx8YvYM4oVU/0gStqX5lpd8qX5/hbdxPPDO3nMz1hH9hXng31ZnKYhqjYF5d
dP78898rM33f
===END CRASH DUMP===

**Comment by robske110** [comment] 2016-03-10 06:26
Looks like an memory leak

**Comment by PEMapModder** [comment] 2016-03-10 09:24
There are too many possible causes to this issue, which might even include plugin causes. Closing, since this issue is not a reproducible issue. As for general memory leak, such issue already exists.

**Closed by PEMapModder** 2016-03-10 09:24 UTC

**Comment by robske110** [comment] 2016-03-10 13:14
Good said
