### ISSUE TITLE
Invalid garbage Chunk given to Entity

### ISSUE THREAD

**Issue by Samueljh1** [PocketMine/PocketMine-MP#3875] opened 2016-01-15 22:38 UTC
Edited by @PEMapModder:

The issue that still exists has the following information:

> Here's another one, that happens when 2 players are killed by 1 single TNT:

> ```
[13:54:41] [Server thread/CRITICAL]: Could not tick level "world": Invalid garbage Chunk given to Entity
[13:54:41] [Server thread/CRITICAL]: pocketmine\utils\ChunkException: "Invalid garbage Chunk given to Entity" (EXCEPTION) in "/src/pocketmine/entity/Entity__64bit" at line 210
[13:54:41] [Server thread/DEBUG]: #0 /src/pocketmine/level/Level__64bit(1491): pocketmine\entity\Entity::createEntity(string Item, pocketmine\level\format\anvil\Chunk object, pocketmine\nbt\tag\Compound pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\Enum:pocketmine\nbt\tag\Enum{.pocketmine\nbt\tag\Double:609.5.pocketmine\nbt\tag\Double:16.5.pocketmine\nbt\tag\Double:-819.5.}.pocketmine\nbt\tag\Enum:pocketmine\nbt\tag\Enum{.pocketmine\nbt\tag\Double:-0.0024078552088078.pocketmine\nbt\tag\Double:0.2.pocketmine\nbt\tag\Double:0.027977234819371.}.pocketmine\nbt\tag\Enum:pocketmine\nbt\tag\Enum{.pocketmine\nbt\tag\Float:279.44812960776.pocketmine\nbt\tag\Float:0.}.pocketmine\nbt\tag\Short:5.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\Short:3.pocketmine\nbt\tag\Byte:1.pocketmine\nbt\tag\Short:0.}.pocketmine\nbt\tag\Short:10.})
[13:54:41] [Server thread/DEBUG]: #1 /src/pocketmine/level/Explosion__64bit(209): pocketmine\level\Level->dropItem(pocketmine\math\Vector3 Vector3(x=609.5,y=16.5,z=-819.5), pocketmine\item\ItemBlock Item Dirt (3:0)x1)
[13:54:41] [Server thread/DEBUG]: #2 /src/pocketmine/entity/PrimedTNT(132): pocketmine\level\Explosion->explodeB(boolean)
[13:54:41] [Server thread/DEBUG]: #3 /src/pocketmine/entity/PrimedTNT(115): pocketmine\entity\PrimedTNT->explode(boolean)
[13:54:41] [Server thread/DEBUG]: #4 /src/pocketmine/level/Level__64bit(701): pocketmine\entity\PrimedTNT->onUpdate(integer 2408)
[13:54:41] [Server thread/DEBUG]: #5 /src/pocketmine/Server__64bit(2324): pocketmine\level\Level->doTick(integer 2408)
[13:54:41] [Server thread/DEBUG]: #6 /src/pocketmine/Server__64bit(2482): pocketmine\Server->checkTickUpdates(integer 2408, double 1452952480.6823)
[13:54:41] [Server thread/DEBUG]: #7 /src/pocketmine/Server__64bit(2222): pocketmine\Server->tick(boolean)
[13:54:41] [Server thread/DEBUG]: #8 /src/pocketmine/Server__64bit(2100): pocketmine\Server->tickProcessor(boolean)
[13:54:41] [Server thread/DEBUG]: #9 /src/pocketmine/Server__64bit(1701): pocketmine\Server->start(boolean)
[13:54:41] [Server thread/DEBUG]: #10 /src/pocketmine/PocketMine(466): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///Users/samuel/SkyWars/PocketMine-MP.phar/, string /Users/samuel/SkyWars/, string /Users/samuel/SkyWars/plugins/)
[13:54:41] [Server thread/DEBUG]: #11 (1): require(string phar:///Users/samuel/SkyWars/PocketMine-MP.phar/src/pocketmine/PocketMine.php)
```

Remarks: This issue is caused by passing a Chunk object to Entity but the Chunk->getProvider() is null.

Old message
===

The first error occurs when a tnt block explodes next to other tnt blocks (the chain reaction)

Here is the error:
[Server thread/CRITICAL]: Could not tick level "world": Class pocketmine\block\Tool not found

Not only this, but when a primedtnt entity explodes next to a [EDIT: player, but the damage is cancelled], this error occurs:

[Server thread/CRITICAL]: Could not tick level "world": Only arrays and Traversables can be unpacked

Note: the bottom error has been happening for many previous versions of pocketmine.

**Comment by PEMapModder** [comment] 2016-01-16 02:04
Enable debug and show stack trace?

**Comment by Samueljh1** [comment] 2016-01-16 09:50
@PEMapModder  Ok ill take a look.

**Comment by Samueljh1** [comment] 2016-01-16 09:53
Nothing shows up, simply a message saying "raising level tick rate to 1."

**Comment by Samueljh1** [comment] 2016-01-16 10:19
Ok found this error for the "tool class not found:"

[10:18:31] [Server thread/CRITICAL]: Could not tick level "world": Class pocketmine\block\Tool not found
[10:18:31] [Server thread/CRITICAL]: ClassNotFoundException: "Class pocketmine\block\Tool not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144
[10:18:31] [Server thread/DEBUG]: #0 /src/pocketmine/block/Stair(146): spl_autoload_call(string pocketmine\block\Tool)
[10:18:31] [Server thread/DEBUG]: #1 /src/pocketmine/level/Explosion__64bit(208): pocketmine\block\Stair->getDrops(pocketmine\item\ItemBlock Item Air (0:0)x1)
[10:18:31] [Server thread/DEBUG]: #2 /src/pocketmine/entity/PrimedTNT(132): pocketmine\level\Explosion->explodeB(boolean)
[10:18:31] [Server thread/DEBUG]: #3 /src/pocketmine/entity/PrimedTNT(115): pocketmine\entity\PrimedTNT->explode(boolean)
[10:18:31] [Server thread/DEBUG]: #4 /src/pocketmine/level/Level__64bit(701): pocketmine\entity\PrimedTNT->onUpdate(integer 2039)
[10:18:31] [Server thread/DEBUG]: #5 /src/pocketmine/Server__64bit(2324): pocketmine\level\Level->doTick(integer 2039)
[10:18:31] [Server thread/DEBUG]: #6 /src/pocketmine/Server__64bit(2482): pocketmine\Server->checkTickUpdates(integer 2039, double 1452939511.0118)
[10:18:31] [Server thread/DEBUG]: #7 /src/pocketmine/Server__64bit(2222): pocketmine\Server->tick(boolean)
[10:18:31] [Server thread/DEBUG]: #8 /src/pocketmine/Server__64bit(2100): pocketmine\Server->tickProcessor(boolean)
[10:18:31] [Server thread/DEBUG]: #9 /src/pocketmine/Server__64bit(1701): pocketmine\Server->start(boolean)
[10:18:31] [Server thread/DEBUG]: #10 /src/pocketmine/PocketMine(466): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///Users/samuel/SkyWars/PocketMine-MP.phar/, string /Users/samuel/SkyWars/, string /Users/samuel/SkyWars/plugins/)
[10:18:31] [Server thread/DEBUG]: #11 (1): require(string phar:///Users/samuel/SkyWars/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

**Comment by Samueljh1** [comment] 2016-01-16 10:19
The issue above is caused by the "stair" class, on line 146

**Comment by Samueljh1** [comment] 2016-01-16 10:28
for some reason, 

public function getDrops(Item $item){
		if($item->isPickaxe() >= Tool::TIER_WOODEN){
			return [
				[$this->getId(), 0, 1],
			];
		}else{
			return [];
		}
	}

Tool:: is accessed as pocketmine\blook\Tool although the import in the class is pocketmine\item\Tool

**Comment by PEMapModder** [comment] 2016-01-16 12:19
0b42ead
Make sure your PocketMine version is correct?

**Comment by Samueljh1** [comment] 2016-01-16 12:40
it should be, i checked the source and that line is there. But clearly, thats the issue.

**Comment by Samueljh1** [comment] 2016-01-16 12:40
*Still the second problem lol

**Comment by PEMapModder** [comment] 2016-01-16 12:41
Stack trace?

**Comment by Samueljh1** [comment] 2016-01-16 12:49
Haven't managed to replicate the error...

**Comment by robske110** [comment] 2016-01-16 13:04
Just  an remark: Never happened to me while using pocketmine and never happened to me on |€€Imag(:7525)ical)73-):7Mine3)51

**Comment by Samueljh1** [comment] 2016-01-16 13:56
Here's another one, that happens when 2 players are killed by 1 single TNT:

13:54:41] [Server thread/CRITICAL]: Could not tick level "world": Invalid garbage Chunk given to Entity
[13:54:41] [Server thread/CRITICAL]: pocketmine\utils\ChunkException: "Invalid garbage Chunk given to Entity" (EXCEPTION) in "/src/pocketmine/entity/Entity__64bit" at line 210
[13:54:41] [Server thread/DEBUG]: #0 /src/pocketmine/level/Level__64bit(1491): pocketmine\entity\Entity::createEntity(string Item, pocketmine\level\format\anvil\Chunk object, pocketmine\nbt\tag\Compound pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\Enum:pocketmine\nbt\tag\Enum{.pocketmine\nbt\tag\Double:609.5.pocketmine\nbt\tag\Double:16.5.pocketmine\nbt\tag\Double:-819.5.}.pocketmine\nbt\tag\Enum:pocketmine\nbt\tag\Enum{.pocketmine\nbt\tag\Double:-0.0024078552088078.pocketmine\nbt\tag\Double:0.2.pocketmine\nbt\tag\Double:0.027977234819371.}.pocketmine\nbt\tag\Enum:pocketmine\nbt\tag\Enum{.pocketmine\nbt\tag\Float:279.44812960776.pocketmine\nbt\tag\Float:0.}.pocketmine\nbt\tag\Short:5.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\Short:3.pocketmine\nbt\tag\Byte:1.pocketmine\nbt\tag\Short:0.}.pocketmine\nbt\tag\Short:10.})
[13:54:41] [Server thread/DEBUG]: #1 /src/pocketmine/level/Explosion__64bit(209): pocketmine\level\Level->dropItem(pocketmine\math\Vector3 Vector3(x=609.5,y=16.5,z=-819.5), pocketmine\item\ItemBlock Item Dirt (3:0)x1)
[13:54:41] [Server thread/DEBUG]: #2 /src/pocketmine/entity/PrimedTNT(132): pocketmine\level\Explosion->explodeB(boolean)
[13:54:41] [Server thread/DEBUG]: #3 /src/pocketmine/entity/PrimedTNT(115): pocketmine\entity\PrimedTNT->explode(boolean)
[13:54:41] [Server thread/DEBUG]: #4 /src/pocketmine/level/Level__64bit(701): pocketmine\entity\PrimedTNT->onUpdate(integer 2408)
[13:54:41] [Server thread/DEBUG]: #5 /src/pocketmine/Server__64bit(2324): pocketmine\level\Level->doTick(integer 2408)
[13:54:41] [Server thread/DEBUG]: #6 /src/pocketmine/Server__64bit(2482): pocketmine\Server->checkTickUpdates(integer 2408, double 1452952480.6823)
[13:54:41] [Server thread/DEBUG]: #7 /src/pocketmine/Server__64bit(2222): pocketmine\Server->tick(boolean)
[13:54:41] [Server thread/DEBUG]: #8 /src/pocketmine/Server__64bit(2100): pocketmine\Server->tickProcessor(boolean)
[13:54:41] [Server thread/DEBUG]: #9 /src/pocketmine/Server__64bit(1701): pocketmine\Server->start(boolean)
[13:54:41] [Server thread/DEBUG]: #10 /src/pocketmine/PocketMine(466): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///Users/samuel/SkyWars/PocketMine-MP.phar/, string /Users/samuel/SkyWars/, string /Users/samuel/SkyWars/plugins/)
[13:54:41] [Server thread/DEBUG]: #11 (1): require(string phar:///Users/samuel/SkyWars/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

**Comment by Samueljh1** [comment] 2016-01-16 15:54
Ok, got the last error:

[15:53:50] [Server thread/CRITICAL]: Could not tick level "world": Only arrays and Traversables can be unpacked
[15:53:50] [Server thread/WARNING]: RuntimeException: "Only arrays and Traversables can be unpacked" (E_WARNING) in "/src/pocketmine/level/Explosion__64bit" at line 209
[15:53:50] [Server thread/DEBUG]: #0 /src/pocketmine/entity/PrimedTNT(132): pocketmine\level\Explosion->explodeB(boolean)
[15:53:50] [Server thread/DEBUG]: #1 /src/pocketmine/entity/PrimedTNT(115): pocketmine\entity\PrimedTNT->explode(boolean)
[15:53:50] [Server thread/DEBUG]: #2 /src/pocketmine/level/Level__64bit(701): pocketmine\entity\PrimedTNT->onUpdate(integer 1279)
[15:53:50] [Server thread/DEBUG]: #3 /src/pocketmine/Server__64bit(2324): pocketmine\level\Level->doTick(integer 1279)
[15:53:50] [Server thread/DEBUG]: #4 /src/pocketmine/Server__64bit(2482): pocketmine\Server->checkTickUpdates(integer 1279, double 1452959630.0483)
[15:53:50] [Server thread/DEBUG]: #5 /src/pocketmine/Server__64bit(2222): pocketmine\Server->tick(boolean)
[15:53:50] [Server thread/DEBUG]: #6 /src/pocketmine/Server__64bit(2100): pocketmine\Server->tickProcessor(boolean)
[15:53:50] [Server thread/DEBUG]: #7 /src/pocketmine/Server__64bit(1701): pocketmine\Server->start(boolean)
[15:53:50] [Server thread/DEBUG]: #8 /src/pocketmine/PocketMine(466): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///Users/samuel/SkyWars/PocketMine-MP.phar/, string /Users/samuel/SkyWars/, string /Users/samuel/SkyWars/plugins/)
[15:53:50] [Server thread/DEBUG]: #9 (1): require(string phar:///Users/samuel/SkyWars/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

**Comment by 0kino7ori** [comment] 2016-02-04 01:47
Looks like Block::getDrops() returns [ [ ] , ] when it shoud return a simple [ ] array. 
Explosion::explodeB() calls Item::get() with an array argument on line 209:
`$this->level->dropItem($block->add(0.5, 0.5, 0.5), Item::get(...$drop));`
but $drop is coming from Block::getDrops() and it's a not an array as it should be to be unpacked to match Item::get() arguments.

**Comment by 0kino7ori** [comment] 2016-02-04 05:15
Yep, I have changed the getDrops definition (return statement) and it seems to have corrente my issues.
before:
`public function getDrops(Item $item){
		if(!isset(self::$list[$this->getId()])){ //Unknown blocks
			return [];
		}else{
			return [
                              [$this->getId(), $this->getDamage(), 1],
                              ];
		}
	}`

after:
`public function getDrops(Item $item){
		if(!isset(self::$list[$this->getId()])){ //Unknown blocks
			return [];
		}else{
			return [$this->getId(), $this->getDamage(), 1];
		}
	}`

**Comment by 0kino7ori** [comment] 2016-02-04 08:02
But it looks like a workaround, while I believe getDrops() method does not feel right.
It was supposed to return an array of 
`[$this->getId(), $this->getDamage(), 1]`
and not only one tuplet/array.
In addition, the argument Item $item is not used anywhere inside the method...

**Comment by Samueljh1** [comment] 2016-02-04 08:12
Send a PR

**Comment by 0kino7ori** [comment] 2016-02-05 02:33
Sent PR #3927 which might address this issue.

**Comment by 0kino7ori** [comment] 2016-02-07 04:11
I had your second issue and it also happens right after a Explosion::explodeB() call.
I am pretty sure it has something to do with the argument notation in Item::get(...$drop).
The PR I sent was bad and I will run some tests by adding this check inside explosionB() and see if it solves the critical message.

```
if (!empty($drop)) //include this check
    $this->level->dropItem($block->add(0.5, 0.5, 0.5), Item::get(...$drop)); //existing line inside foreach loop
```

**Comment by 0kino7ori** [comment] 2016-02-07 04:15
Or maybe just change it to:

`$this->level->dropItem($block->add(0.5, 0.5, 0.5), Item::get($drop[0], $drop[1], $drop[2]);`

**Comment by PEMapModder** [comment] 2016-02-10 04:55
Actually, is there more than one bug? One issue per bug, please.

**Comment by PEMapModder** [comment] 2016-02-17 12:16
I suspect the issue related to array unpacking has been fixed by cfca0a8726418efb6990d9ba7da2c4397e8609b7

**Comment by 0kino7ori** [comment] 2016-02-23 18:00
Thank you for the update

**Comment by PEMapModder** [comment] 2016-03-07 10:28
Please comment to reopen if this issue can still be reproduced.

**Closed by PEMapModder** 2016-03-07 10:28 UTC

**Comment by Samueljh1** [comment] 2016-03-07 16:15
Yes, that was the cause of the issue. The PR has fixed this, and there were tall grass blocks present in the testing.

**Comment by PEMapModder** [comment] 2016-03-07 16:55
@Samueljh1 are you sure that "Invalid garbage Chunk given to Entity" is related to that PR?

**Comment by Samueljh1** [comment] 2016-03-07 19:17
It was to do with the unpacking issue.

**Comment by PEMapModder** [comment] 2016-03-07 19:29
@Samueljh1 so if you think that the issue persists, please provide the steps to reproduce the issue.
